### ISSUE TITLE
LRS Dashboard | Most Active Users Breaks

### ISSUE THREAD

**Issue by SundarPPE** [LearningLocker/learninglocker#277] opened 2014-06-26 09:18 UTC
When I update the Following  Statement without mbox,

{
    "actor": {
        "name": "test20 test",
        "account": {
            "homePage": "http://example.com",
            "name": "dc889da948244626b5bae87a4a28bc67"
        }
    },
    "verb": {
        "id": "https://adl.gov/verbs/attempted",
        "display": {
            "en-US": "attempted"
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "http://example.com/activity",
        "definition": {
            "name": {
                "en-US": "Activity"
            }
        }
    }
}

the Most Active Users in the LRS Dashboard Breaks,

Thanks
Sundar

**Comment by ryansmith94** [comment] 2015-02-12 11:58
Hi @SundarPPE, this should be fixed in the [issue/277](https://github.com/LearningLocker/learninglocker/tree/issue/277) branch. If you can pull and test that branch that would be helpful. Once you confirm that the issue is fixed for you I'll make a pull request out of that branch.

Thanks for reporting this, apologies that this has taken so long, it just wasn't a high priority.

**Closed** 2015-02-13 10:12 UTC
Labels: priority:low, status:unmerged, type:enhancement
