### ISSUE TITLE
Statement button in report generates a MongoDB error

### ISSUE THREAD

**Issue by denhamd** [LearningLocker/learninglocker#826] opened 2016-06-14 18:02 UTC
**Version**
1.12.1

**Steps to reproduce the bug**
1. Generate tests statements using the tincanapi.com generator.
2. Start working with reports.
3. Press the statements button in the report.

**Expected behaviour**
The display should be a list of statements matching the report filters.

**Actual behaviour**
The display is an error screen (with details given below).

```
Pressing the Statements button results in MongoCollection::find(): expects parameter 2 to be an array or object, null given.
/var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php line 59 - $result = call_user_func_array(array($this->collection, $method), $parameters);
```

**Server information**
Ubuntu 14.04 64 bit.
Mongo Community 3.2.7
Mongo PHP driver 1.6.14

**Client information**
OS: Windows 7
Browser: Firefox version 46

**Comment by ht2** [comment] 2016-06-15 08:26
Could you please post more of the stack trace?

**Comment by denhamd** [comment] 2016-06-15 12:40
Here it is.

Open: /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php <subl://open?url=file:/%2Fvar%2Fwww%2Flearninglocker%2Fvendor%2Fjenssegers%2Fmongodb%2Fsrc%2FJenssegers%2FMongodb%2FCollection.php&line=59>

  1.              {
  2.                  $query[] = '{...}';
  3.              }
  4.          }
  5.
  6.          $start = microtime(true);
  7.
  8.          $result = call_user_func_array(array($this->collection, $method), $parameters);
  9.
  10.         // Once we have run the query we will calculate the time that it took to run and
GET Data empty
POST Data empty
Files empty
Cookies
_ga

GA1.2.636569140.1442000029

__utma

218621063.636569140.1442000029.1464899393.1465247901.13

__utmz

218621063.1465247901.13.10.utmcsr=search.okstate.edu|utmccn=(referral)|utmcmd=referral|utmcct=/index.htm

AMCV_774C31DD5342CAF40A490D44@AdobeOrg

793872103|MCIDTS|16843|MCMID|36691989515890656352093428924638102327|MCAAMLH-1455812226|9|MCAAMB-1455812226|cIBAx_aQzFEHcPoEv0GwcQ|MCAID|NONE

s_cc

true

__utmc

218621063

laravel_session

eyJpdiI6IjFqRXBCOGJUSkE0cWVzaDNsak1HQmVHdWFQeDEwSXdGOHROMWRNcTBmSms9IiwidmFsdWUiOiIxYkV6NEJTc3NoeVBHaUVJd21cL2RMVDRLY0JqakI1amFlbGhMZ1NCeXlmWkJWdTVLeGlMODYrSUxDR1hSK21JT0ZpaDF4TlA5TTZPejV4YU0wOUorZFE9PSIsIm1hYyI6IjllNTRkNTMyNjE1M2Q1Mjc3MGM0YmQ5YmJhMmQ4NmJjNjY0ZmFkMzZjMjFmZWEyN2JkYzAzZWVjN2U1YWEwZTYifQ==

Session empty
Server/Request Data
REDIRECT_STATUS

200

HTTP_HOST

gracie.lib.okstate.edu

HTTP_USER_AGENT

Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

HTTP_ACCEPT

text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

HTTP_ACCEPT_LANGUAGE

en-US,en;q=0.5

HTTP_ACCEPT_ENCODING

gzip, deflate

HTTP_DNT

1

HTTP_REFERER

http://gracie.lib.okstate.edu/lrs/57600c77d02a68280a8b4567/reporting

HTTP_COOKIE

_ga=GA1.2.636569140.1442000029; __utma=218621063.636569140.1442000029.1464899393.1465247901.13; __utmz=218621063.1465247901.13.10.utmcsr=search.okstate.edu|utmccn=(referral)|utmcmd=referral|utmcct=/index.htm; AMCV_774C31DD5342CAF40A490D44%40AdobeOrg=793872103%7CMCIDTS%7C16843%7CMCMID%7C36691989515890656352093428924638102327%7CMCAAMLH-1455812226%7C9%7CMCAAMB-1455812226%7CcIBAx_aQzFEHcPoEv0GwcQ%7CMCAID%7CNONE; s_cc=true; __utmc=218621063; laravel_session=eyJpdiI6IjFqRXBCOGJUSkE0cWVzaDNsak1HQmVHdWFQeDEwSXdGOHROMWRNcTBmSms9IiwidmFsdWUiOiIxYkV6NEJTc3NoeVBHaUVJd21cL2RMVDRLY0JqakI1amFlbGhMZ1NCeXlmWkJWdTVLeGlMODYrSUxDR1hSK21JT0ZpaDF4TlA5TTZPejV4YU0wOUorZFE9PSIsIm1hYyI6IjllNTRkNTMyNjE1M2Q1Mjc3MGM0YmQ5YmJhMmQ4NmJjNjY0ZmFkMzZjMjFmZWEyN2JkYzAzZWVjN2U1YWEwZTYifQ%3D%3D

HTTP_CONNECTION

keep-alive

PATH

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

SERVER_SIGNATURE

<address>Apache/2.4.7 (Ubuntu) Server at gracie.lib.okstate.edu Port 80</address>

SERVER_SOFTWARE

Apache/2.4.7 (Ubuntu)

SERVER_NAME

gracie.lib.okstate.edu

SERVER_ADDR

139.78.31.94

SERVER_PORT

80

REMOTE_ADDR

139.78.30.150

DOCUMENT_ROOT

/var/www/learninglocker/public

REQUEST_SCHEME

http

CONTEXT_PREFIX

CONTEXT_DOCUMENT_ROOT

/var/www/learninglocker/public

SERVER_ADMIN

mail@gracie.lib.okstate.edu

SCRIPT_FILENAME

/var/www/learninglocker/public/index.php

REMOTE_PORT

58453

REDIRECT_URL

/lrs/57600c77d02a68280a8b4567/reporting/57603a0ad02a68df058b4568/statements

GATEWAY_INTERFACE

CGI/1.1

SERVER_PROTOCOL

HTTP/1.1

REQUEST_METHOD

GET

QUERY_STRING

REQUEST_URI

/lrs/57600c77d02a68280a8b4567/reporting/57603a0ad02a68df058b4568/statements

SCRIPT_NAME

/index.php

PHP_SELF

/index.php

REQUEST_TIME_FLOAT

1465926483.411

REQUEST_TIME

1465926483

Environment Variables empty
Registered Handlers

**Comment by ht2** [comment] 2016-06-15 13:43
Sorry @denhamd but if you look in your error logs you will find a full trace of the error, that is what we are looking for

**Comment by denhamd** [comment] 2016-06-15 15:25
Is this what you wanted?

**Comment by denhamd** [comment] 2016-06-20 13:34
@ryansmith94, installed LL on a new VM except this time I installed mongo 2.6.12. Same error as before. Then I upgraded to LL 1.13.0. Again no change. Any suggestions?

**Comment by ht2** [comment] 2016-06-20 14:44
@denhamd We can't debug this any further without you finding the full stack trace for the error. What you have posted above is useful, but it doesn't help us track down _where_ the issue is triggered from. By finding this error in you error logs (look in `app/storage/logs`) you will see that the full stack trace depicts every file and line that the error passes back through. Once we can see that we'll have half a chance of diagnosing, but until then we're no wiser than you as to the problem!

**Comment by denhamd** [comment] 2016-06-20 15:44
@ht2 the attached files represent the entire contents of app/storage/logs with the exception of .gitignore.  If these files are incomplete is there some option that I need to enable?

[laravel-2016-06-17.txt](https://github.com/LearningLocker/learninglocker/files/323767/laravel-2016-06-17.txt)
[laravel-2016-06-20.txt](https://github.com/LearningLocker/learninglocker/files/323768/laravel-2016-06-20.txt)

**Comment by denhamd** [comment] 2016-06-20 15:45
@ht2 Forgot to add that I renamed them to .txt since the .zip containing them wouldn't attach to the comment

**Comment by ht2** [comment] 2016-06-20 15:57
Thanks @denhamd, we'll take a look

**Comment by denhamd** [comment] 2016-06-22 12:42
@ht2 I'm getting some pressure from higher ups to get LL going or I'll have to start looking at other solutions.  Any idea of when a fix might be coming or is there anything I can do to facilitate the process?
Thanks

**Comment by ryansmith94** [comment] 2016-06-22 12:48
@denhamd, it's not actually clear what is causing these errors from the steps you given us to reproduce the issue. We have instances of Learning Locker running with millions of statements without this issue. We need more detailed steps to reproduce the issue.

**Comment by hallshouse** [comment] 2016-06-22 13:05
@ht2 @ryansmith94 I have exactly this same issue.
Log attached.
[laravel-2016-06-22.txt](https://github.com/LearningLocker/learninglocker/files/327892/laravel-2016-06-22.txt)

**Comment by ht2** [comment] 2016-06-22 13:10
Looks like it is something to do with the way the hinting for the new counts are used in 1.13. Needs looking at, I'll look to formally descirbe and create the issue. @denhamd apologies, but I can't give you a time frame on this. We're an open source community so rely on others as much as ourselves to push fixes and develop the product.

**Comment by denhamd** [comment] 2016-06-22 13:11
@ryansmith94 it just occurred to me that the statements I'm using might be the problem so I'm including a few of them.  They were generated with the tincanapi.com statement generator.  Basically I'm a server admin that doesn't know much about LRSs or xapi that has been tasked with setting this up.  I can forward the installation steps I use to set up LL if that will help.

________________________________

**Comment by ht2** [comment] 2016-06-22 13:13
One thing I will note @hallshouse, this error in your log...
```
[2016-06-22 12:43:17] local.ERROR: exception 'ErrorException' with message 'MongoCollection::count() expects parameter 2 to be long, array given' in /var/www/learninglocker/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php:59
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'MongoCollection...', '/var/www/learni...', 59, Array)
#1 [internal function]: MongoCollection->count(Array, Array)
```

To me, this does not fit with the requirements in the documentation for MongoCollection:
http://php.net/manual/en/mongocollection.count.php

The error is that `count() expects parameter 2 to be long`. That is actually not true according to the documentation, an array _should_ be what is passed!

**Comment by ryansmith94** [comment] 2016-06-22 13:17
Is it possible that this error is occuring because the index doesn't exist @ht2? That might explain why we can't reproduce this issue. Note that the logs from both @denhamd and @hallshouse contain the following errors at the top.

@denhamd 
```
[2016-06-22 12:21:19] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method MongoCollection::createIndex()' in /var/www/learninglocker/app/database/migrations/2015_12_23_093122_add_stored_to_statement_root.php:20
```

@hallshouse 
```
[2016-06-17 21:59:06] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method MongoCollection::createIndex()' in /var/www/learninglocker/app/database/migrations/2015_12_23_093122_add_stored_to_statement_root.php:20
```

**Comment by hallshouse** [comment] 2016-06-22 13:19
@ht2 I'm not sure what I can do here, I'm running MongoDB 2.6.12, and LL 1.13.0 on a new Ubuntu 14.04 installation.
Should I reinstall using an older MongoDB version?

**Comment by ryansmith94** [comment] 2016-06-22 13:23
@hallshouse, certainly wouldn't try to use an older MongoDB version. If any thing go for a newer MongoDB version or an older version of LL. Just a quick question to you both @denhamd and @hallshouse, when you ran `php artisan migrate --env=YOUR_ENV`, did you change `YOUR_ENV` to `local`?

**Comment by ht2** [comment] 2016-06-22 13:23
Interesting - certainly that is an issue, but doesn't explain why it is throwing a type error. Here is one of the instances where we use the hinting on counts:

https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/repository/Statement/EloquentIndexer.php#L237

Note the second argument is the hint passed into the builder's `count` method. If you follow this through to the _forked_ version of jensegger's library that 1.13 requires you can see that the collection is passed this information. 
https://github.com/LearningLocker/laravel-mongodb/blob/issue/count-0.0.2/src/Jenssegers/Mongodb/Query/Builder.php#L353

I'm wondering... have you both done a `composer install` since updating? I wonder if your versions are both using the forked version of the library (as declared in https://github.com/LearningLocker/learninglocker/blob/master/composer.json#L45) or if they are still using the master from jenseggers. 

@hallshouse, could you look into your `/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php` and tell me if line 1089 looks like this... https://github.com/LearningLocker/laravel-mongodb/blob/issue/count-0.0.2/src/Jenssegers/Mongodb/Query/Builder.php#L1089

**Comment by ht2** [comment] 2016-06-22 13:25
I've just double checked and the [`composer.lock`](https://github.com/LearningLocker/learninglocker/blob/develop/composer.lock#L1029) is definitely requiring the correct branch+fork.

**Comment by hallshouse** [comment] 2016-06-22 13:30
I did not do an upgrade, I did a fresh install (Ubuntu and all) and only used `sudo php artisan migrate` as I have always done. I did captuire an error result after this but have had the following error before from this command:
`Foreign id values in client collection converted from string to MongoId.
PHP Fatal error:  Call to undefined method MongoCollection::createIndex() in /var/www/learninglocker/app/database/migrations/2015_12_23_093122_add_stored_to_statement_root.php on line 20
Status: 500 Error: Call to undefined method MongoCollection::createIndex(){"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method MongoCollection::createIndex()","file":"\/var\/www\/learninglocker\/app\/database\/migrations\/2015_12_23_093122_add_stored_to_statement_root.php","line":20}}`

**Comment by denhamd** [comment] 2016-06-22 13:30
@ryansmith94 I'm using mongo 2.6.12 as well. Also the installation instructions I have simply specify "sudo php artisan migrate".  @ht2 I don't believe I've done a "composer install" since updating.  How could I tell for sure?  I based my install on jPablo's instructions but modified to account for the 1.6.4 driver.

**Comment by ryansmith94** [comment] 2016-06-22 13:37
Could you try running `php artisan migrate --env=local` @denhamd @hallshouse?

**Comment by ht2** [comment] 2016-06-22 13:39
OK, think we are starting to get to the bottom of two (three?) problems here.

1. @hallshouse: I don't understand why the `MongoCollection::createIndex()` isn't working for you, but that is a documented method on the PHP Mongo driver for MongoCollection and we have seen it working many times. You may need to double check the version of the driver you are using. The hinting will _definetly_ not work unless you have the indexes, hence I added them as part of the migration (note that this all works fine in the [Travis builds](https://travis-ci.org/LearningLocker/learninglocker/builds/138299910#L921), our local dev environments and multiple installed instances).

2. @denhamd @hallshouse on the `count()` issue, I suspect the application isn't using the new forked branch for the `laravel-mongodb` package. Try deleting your `/vendors` folder and running `composer install` to ensure you have the right version. To double check, dive into the file I listed above and see if it looks right

**Comment by hallshouse** [comment] 2016-06-22 13:39
@ht2 In answer to your "Interesting - certainly that is an issue, but doesn't explain why..." comment;
I'm wondering... have you both done a  composer install  since updating? Yes, my Composer part of the process is as follows:
```
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
cd /var/www/learninglocker/
sudo composer update (enter token with this command)
sudo composer install

```
Then I do:
sudo php artisan migrate and receive the following error:
```
Foreign id values in client collection converted from string to MongoId.
PHP Fatal error:  Call to undefined method MongoCollection::createIndex() in /var/www/learninglocker/app/database/migrations/2015_12_23_093122_add_stored_to_statement_root.php on line 20
Status: 500 Error: Call to undefined method MongoCollection::createIndex(){"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method MongoCollection::createIndex()","file":"\/var\/www\/learninglocker\/app\/database\/migrations\/2015_12_23_093122_add_stored_to_statement_root.php","line":20}}

```
Also, I just did the ` php artisan migrate --env=local ` and got the same error.

**Comment by denhamd** [comment] 2016-06-22 13:43
@ryansmith94 I tried **php artisan migrate** and received **Module 'mongo' already loaded in Unknown on line 0  Could not open input file: artisan**

**Comment by ht2** [comment] 2016-06-22 13:47
@hallshouse - two separate issues, the composer install won't solve your PHP driver issue. That error is declaring that the method `createIndex` doesn't exist on the PHP MongoCollection class, which is most defintely should!!! Do a `phpinfo()` and see which version of the driver you have - grab a screenshot of the relevant Mongo section if you could

As to the `composer install`, that should have ensured you have the right file. Can you confirm the contents of `vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php` at line 1089?

**Comment by ht2** [comment] 2016-06-22 13:48
@denhamd - that's a PHP error, sounds like you have the mongo extension loaded twice in your config.

**Comment by hallshouse** [comment] 2016-06-22 13:52
Mongo Driver version 1.4.5? That doesn't sound right...\

**Comment by ht2** [comment] 2016-06-22 13:59
No, that is too old!

http://pecl.php.net/package/mongo

Specifically 2.5 years old! (2013-11-05)

**Comment by ht2** [comment] 2016-06-22 14:01
http://pecl.php.net/package-info.php?package=mongo&version=1.5.0 allowed support for createIndex, but I would _strongly_ recommend going with latest and greatest!!!

**Comment by hallshouse** [comment] 2016-06-22 14:03
@ht2 for sure, doing it now. Not sure why that version of the driver installed.

**Comment by denhamd** [comment] 2016-06-22 14:11
@ht2 Sorry - finger slip - I meant 1.6.14, from the link on the LL installation page.  I work in a Windows shop so I'm new to Linux. I'm building my own installation procedure based on commonalities in all the documentation there, however most of current version came from jPablo's procedure.

**Comment by hallshouse** [comment] 2016-06-22 14:11
@ht2 Since when do we need to install php5-dev to get the correct mongo driver?
Are you all having to do this?

**Comment by hallshouse** [comment] 2016-06-22 14:14
@ht2 I'll rebuild my server from scratch again and go with mongo3

**Comment by ht2** [comment] 2016-06-22 14:39
Yea the mongo driver seems to have some odd requierements, `php5-dev` or `php5-devel` seem to crop up a fair bit. Where possible use PECL as it takes the headache out of it. The jPablo guide is unfortiunately just really out of date now. David Pesce's one is much better and is for Centos 7 (which is great) https://gist.github.com/davidpesce/7d6e1b81594ecbc72311

**Comment by hallshouse** [comment] 2016-06-22 14:42
@ht2 I don't use that guide, I developed my own procedure last year and update it as needed (today being an "as needed" day)

**Comment by ht2** [comment] 2016-06-22 14:43
Haha! good stuff.

@denhamd let me know once you have confirmed the status of the `vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php` file...

**Comment by hallshouse** [comment] 2016-06-22 14:45
@ht2 So, FYI, I've just confirmed the mongo driver issue is specifically being called by the php5 production install. I'll use PECL and get the php5-dev version.

**Comment by hallshouse** [comment] 2016-06-22 15:04
@ht2 I've installed php5-dev and mongo3.0 and still get the 1.4.5 driver. I'm on ubuntu 14.04 prod.
Have you seen this issue?

**Comment by ht2** [comment] 2016-06-22 15:05
No sorry, we install the Mongo driver through PECL which i'd advise where possible

**Comment by hallshouse** [comment] 2016-06-22 15:05
Ah crap, I just installed the dev NOT FROM PECL  process ~!@##$@#$

**Comment by hallshouse** [comment] 2016-06-22 15:06
Time for another install...

**Comment by hallshouse** [comment] 2016-06-22 16:43
@ht2 @ryansmith94 Everything is working perfectly for me now. The PECL MongoDB install was the solution. This issue is closed for me now.

Thanks for your patients.

**Comment by denhamd** [comment] 2016-06-22 16:51
@hallshouse Would you mind sharing your install procedure?

**Comment by ht2** [comment] 2016-06-22 16:54
@denhamd This guide uses the PECL Mongo package and is very good: 
https://gist.github.com/davidpesce/7d6e1b81594ecbc72311

**Comment by hallshouse** [comment] 2016-06-22 17:12
@denhamd Here is my "very granular" installation procedure I used today.
[Installing LearningLocker on Ubuntu 14.04 Minimal.txt](https://github.com/LearningLocker/learninglocker/files/328372/Installing.LearningLocker.on.Ubuntu.14.04.Minimal.txt)

**Comment by denhamd** [comment] 2016-06-22 19:02
@hallshouse Thanks for the procedure. I'm glad it worked for you. Unfortunately I still have the same error even after doing a fresh install.  I'm going to try the procedure @ht2 suggested to see if I can get something going but I will be going back over yours to see if I missed something.  BTW: the part about updating database.php with the new mongo credentials is missing.

**Comment by hallshouse** [comment] 2016-06-22 19:07
@denhamd I did not need to do that in this procedure, nor have I ever had update database.php since version 1.5 or 1.4.

Are you installing on Ubuntu?

**Comment by denhamd** [comment] 2016-06-22 19:22
Yes 14.04.4 LTS

**Comment by hallshouse** [comment] 2016-06-22 19:47
Have you done a `sudo apt-get dist-upgrade` ?
If yes, what step # I'm my procedure are you failing at?

**Comment by denhamd** [comment] 2016-06-22 19:52
Yes I did a `sudo apt-get dist-upgrade`.  I get through the entire procedure and I'm able to login to LL. Its just that the procedure did not appear to mitigate the error I get when I press the statements button in Reporting.

**Comment by hallshouse** [comment] 2016-06-22 19:59
I had this exact issue, the issue I had was that my PHP-Mongo driver was at 1.4.5 when installing MongoDB not from PECL.
If you see my procedure, steps 9, 11, 13, 14, and 17 specifically, they are the correction to the crash that both you and I were having. These steps will install MongoDB 3.0 and the 1.6.4 php5-mongo driver.

**Comment by denhamd** [comment] 2016-06-22 20:06
@hallshouse I did all of those.  I verified that mongo is version 3.0.12 and php mongo driver is 1.6.14.  Are you sure you have 1.6.4 installed?

**Comment by hallshouse** [comment] 2016-06-22 20:25
@denhamd  Sorry, type-o:
Here is my configuration ( per phpinfo )
PHP Version 5.5.9-1ubuntu4.17
System: Linux lrs 2.6.32-43-pve #1 SMP Tue Oct 27 09:55:55 CET 2015 x86_64 

----PHP----
PHP API  20121113  
PHP Extension  20121212  
Zend Extension  220121212  
Zend Extension Build  API220121212,NTS  
PHP Extension Build  API20121212,NTS  
Thread Safety  disabled  
Zend Signal Handling  disabled  
Zend Memory Manager  enabled  
Zend Multibyte Support  provided by mbstring  

----Apache2----
Apache Version  Apache/2.4.7 (Ubuntu)  
Loaded Modules  core mod_so mod_watchdog http_core mod_log_config mod_logio mod_version mod_unixd mod_access_compat mod_alias mod_auth_basic mod_authn_core mod_authn_file mod_authz_core mod_authz_host mod_authz_user mod_autoindex mod_deflate mod_dir mod_env mod_filter mod_mime prefork mod_negotiation mod_php5 mod_rewrite mod_setenvif mod_status  
DOCUMENT_ROOT  /var/www/html  

----cURL---
cURL Information  7.35.0  

----json----
json support  enabled  
json version  1.3.2  
JSON-C version (bundled)  0.11  

----M-Crypt----
mcrypt support: enabled
mcrypt_filter support: enabled
Version  2.5.8  
Api No  20021217  
Supported ciphers  cast-128 gost rijndael-128 twofish arcfour cast-256 loki97 rijndael-192 saferplus wake blowfish-compat des rijndael-256 serpent xtea blowfish enigma rc2 tripledes  
Supported modes  cbc cfb ctr ecb ncfb nofb ofb stream  

----Mongo----
MongoDB Support: enabled
Version  1.6.14  
Streams Support  enabled  
SSL Support  enabled  
Supported Authentication Mechanisms
MONGODB-CR  enabled  
SCRAM-SHA-1  enabled  
MONGODB-X509  enabled  
GSSAPI (Kerberos)  disabled  
PLAIN  disabled  
Directive                                         Local Value                                       Master Value
mongo.allow_empty_keys                   0                                                          0 
mongo.chunk_size                          261120                                                261120 
mongo.cmd                                          $                                                         $ 
mongo.default_host                        localhost                                             localhost 
mongo.default_port                          27017                                                  27017 
mongo.is_master_interval                  15                                                        15 
mongo.long_as_object                        0                                                          0 
mongo.native_long                              1                                                          1 
mongo.ping_interval                            5                                                          5 

Try my procedure from a Ubuntu minimal build with nothing configured at all.

**Comment by denhamd** [comment] 2016-06-22 20:53
@hallshouse Everything you listed matches except Document_Root. Mine is /var/www/learninglocker/public

**Comment by hallshouse** [comment] 2016-06-23 11:15
@denhamd I don't see how that would cause your error.

**Comment by salexfo** [comment] 2016-06-23 11:46
HI, I'm experiencing the same issue. However my driver version is 1.6.14.
I'm on Amazon ec2. What can be the reason here?

**Comment by ht2** [comment] 2016-06-23 11:53
@salexfo could you look into your /vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php and tell me if line 1089 looks like this... https://github.com/LearningLocker/laravel-mongodb/blob/issue/count-0.0.2/src/Jenssegers/Mongodb/Query/Builder.php#L1089

**Comment by salexfo** [comment] 2016-06-23 11:56
@ht2 - it does. I was referring to the issue that when clicking under reporting on the statements button you get the following:
 Status: 500 Error: MongoCollection::find(): expects parameter 2 to be an array or object, null given

**Comment by ht2** [comment] 2016-06-23 12:03
@salexfo yes I realise, changes to how `counts()` are performed mean that the pagination is not correctly using the `count()` system which is defined in an updated version of that file. I needed to confirm that you were using the correct version.

Could you run a `composer dump` and then repeat the process (I would still expect it to fail).

**Comment by ht2** [comment] 2016-06-23 12:15
OK, think we have a fix incoming on https://github.com/LearningLocker/laravel-mongodb/commit/0d11581cbcb8c9b7eb76b7cd9583fba33321b005

**Comment by ht2** [comment] 2016-06-23 12:22
To update, the pagination system does not feed the `count` method a `$columns` value. The default implementation will convert this to `['*']` (which would be expected by the `find()` method. I've added some logic to the jenseggers/mongodb fork to ensure that this value is cast correctly. 

An update to LL is being pushed which will reference the new dependency. It will go into `develop` in the first instance, so feel free to merge in changes from there and then run `composer install` to update your dependency.

I will update once the change is all merged into develop

**Comment by salexfo** [comment] 2016-06-23 12:22
@ht2 thank you.

**Comment by ht2** [comment] 2016-06-23 12:48
That PR is now merged. Feel free to merge in `develop` into your local code base and then run `composer install` to pull the new deps

**Closed** 2016-06-23 12:48 UTC
Labels: priority:low, status:unconfirmed, type:bug
