### ISSUE TITLE
I have problem with the "create report" (reports section) and "add export" (export section) buttons.

### ISSUE THREAD

**Issue by dimis283** [LearningLocker/learninglocker#853] opened 2016-08-17 13:30 UTC
You need to replace the parts of this template where you see {{some text}}.

**Version**
{{branch}} at {{commit}} on {{version - found in your copy of the VERSION file}} 

**Steps to reproduce the bug**
1. {{step 1}}
2. {{step 2}}

**Expected behaviour**
{{feature}} should be {{expectedResult}} because {{reason}}.

**Actual behaviour**
{{feature}} is {{actualResult}}.

**Additional information**
OS: {{operatingSystem}}
Browser: {{browser}} version 1.0.1
{{additionalInfo}}

**Comment by dimis283** [comment] 2016-08-17 13:31
When I push them nothing happens.3 days before the  "create report" button was working. Now I have the error (using the "create report" button) at console of chrome "TypeError: Cannot read property 'id' of undefined" What is wrong?

**Comment by ryansmith94** [comment] 2016-08-17 13:34
Hi @dimis283, please update your initial comment.

> You need to replace the parts of this template where you see {{some text}}.

**Comment by hallshouse** [comment] 2016-08-22 11:52
I can confirm this issue.
After upgrading to v1.3.4, the Create Report button in the reporting view does not function.
After upgrading to v.1.3.4 the Add export button in the exporting view does append the URL with "#new", but does nothing.

**Comment by ryansmith94** [comment] 2016-08-22 12:02
Sorry @hallshouse, did you mean v1.13.4?

**Comment by hallshouse** [comment] 2016-08-22 12:29
Thanks for correcting me, I had actually entered v1.3.4 (my mistake).

now I've corrected that by redoing the upgrade procedure found at: http://docs.learninglocker.net/upgrading/ and using v1.13.4

I've run into an issue in doing so:
I'm now getting the following error in the statements view:
Class '\Locker\XApi\Str' not found
It's pointing to: 43.          Helpers::validateAtom(new $class($value));

Any idea what this could be?

**Comment by hallshouse** [comment] 2016-08-22 12:32
Disregard, I failed to run the:
git rm --cached app/config/local -r; git add app/config/local; git commit -m 'Fixes local config.'; php -r "readfile('https://getcomposer.org/installer');" | php; php composer.phar install
Closed.
Getting more coffee!

**Comment by ryansmith94** [comment] 2016-08-22 12:33
No worries @hallshouse 👍 

Ha awesome! Thanks, I was literally about to start replying to that issue. Enjoy your ☕

**Comment by hallshouse** [comment] 2016-08-22 12:36
@ryansmith94 To clarify, my stupidity on the upgrade is closed, but the Create Report and Add export buttons issue is still open.

**Comment by ryansmith94** [comment] 2016-08-22 12:37
Ok thanks @hallshouse 👍

**Comment by ryansmith94** [comment] 2016-09-09 08:09
Hey @hallshouse @dimis283, I need some steps to reproduce this issue as I've been unable to reproduce it locally.

**Comment by dimis283** [comment] 2016-09-09 09:10
There is a problem with communication with moodle,maybe not LRS related

**Comment by ryansmith94** [comment] 2016-09-09 09:28
Right ok. I think the issue you're seeing regarding the create export button is a duplicate of #805.

**Comment by ryansmith94** [comment] 2016-10-04 12:29
Hi @dimis283 and @hallshouse, this issue is being closed due to inactivity and will be reopened if it later becomes active.

**Closed by ryansmith94** 2016-10-04 12:29 UTC
Labels: priority:low, status:archived, type:bug
