### ISSUE TITLE
Route lrs/{id}/reporting/getReports is missing.

### ISSUE THREAD

**Issue by pondermatic** [LearningLocker/learninglocker#500] opened 2015-02-05 23:10 UTC
**Version**
develop at 1684eb9b9e029fc9afe80e41b496e69c71487aa9

**Steps to reproduce the bug**
* view a LRS's dashboard, URI `/lrs/{id}`

**Expected behaviour**
All requested resources should be returned by the HTTP server. I'm not actually sure what the route used to display before it was removed.

**Actual behaviour**
There will be a 404 status in the web server's access log for `GET /lrs/{id}/reporting/getReports`.
The following error will be logged to laravel.log
```
[2015-02-05 16:44:29] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in learninglocker\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:148
Stack trace:
#0 learninglocker\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1049): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 learninglocker\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1017): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 learninglocker\vendor\laravel\framework\src\Illuminate\Routing\Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 learninglocker\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 learninglocker\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 learninglocker\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 learninglocker\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 learninglocker\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 learninglocker\public\index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
```

**Server information**
Windows 8.1
Apache 2.4
MongoDB 2.6.0
PHP 5.4.31

**Client information**
OS: Windows 8.1
Browser: Chrome version 40

**Additional information**
The request is coming from `public/assets/js/lrs/collections/ReportCollection.js` and `public/assets/js/lrs/models/ReportModel.js`.
The route was removed 2014-10-21 in commit 0d516c05533e8501388dbea9af9e094d96044d61.

**Comment by ryansmith94** [comment] 2015-02-06 14:03
Hi @pondermatic, thanks for reporting this issue and following our guidelines. This is one that I'm aware of already, but I currently have more important tasks. I will be fixing this soon.

The route was removed when we moved to phase 2 of reports. If you need this endpoint externally please use the [index method in our reports API](http://docs.learninglocker.net/report_api/#index)

**Comment by ryansmith94** [comment] 2015-02-12 11:24
Hi @pondermatic, this should be fixed in the [issue/500](https://github.com/LearningLocker/learninglocker/tree/issue/500) branch. If you can pull and test that branch that would be helpful. Once you confirm that the issue is fixed for you I'll make a pull request out of that branch.

**Comment by pondermatic** [comment] 2015-02-12 20:25
Hi @ryansmith94, I tested the [issue/500](https://github.com/LearningLocker/learninglocker/tree/issue/500) branch and it does indeed fix the old call for `lrs/{id}/reporting/getReports`.

However, now there is an HTTP request for /assets/js/libs/backbone/backbone-min.map that is missing.

**Comment by ryansmith94** [comment] 2015-02-12 21:52
Ok, please raise that as a separate issue.

**Closed** 2015-02-13 10:01 UTC
Labels: priority:low, status:unmerged, type:bug
