### ISSUE TITLE
Having CORS issues on LLv2.  Get 407 error on initial OPTIONS request.

### ISSUE THREAD

**Issue by moneyhan** [LearningLocker/learninglocker#1004] opened 2017-10-22 15:55 UTC
Thinking this is just an Nginx .conf file setup issue.  Have seen lots of examples of general setup.  Wondering if anyone has any examples that include all the other LL entries that are applied during the install.  Also have Lets Encrypt SSL enabled.  Thanks in advance.

**Comment by ht2** [comment] 2017-10-23 09:56
Hi @moneyhan,

Can you please confirm the exact URL you are seeing CORS issues with. It would also be good if you could modify the issue to follow the provided template for new issues available here: https://github.com/LearningLocker/learninglocker/issues/new

**Comment by moneyhan** [comment] 2017-10-23 11:07
Sure,  I can update it:

For right now.

Domain where learning content launching from:  https://webhostqa.dignityhealth.org

Domain where Learning Locker is: https://xpilearn.com

Failing on xhr call to /data/xAPI to get OPTIONS.  Get 407 error.

Thanks

________________________________
On: 23 October 2017 05:56, "James Mullaney" <notifications@github.com<mailto:notifications@github.com>> wrote:

Dignityhealth.org made the following annotations
---------------------------------------------------------------------
STOP, THINK, READ. This is an external email. Exercise extra caution responding to it, opening attachments and following links.
---------------------------------------------------------------------

Hi @moneyhan<https://github.com/moneyhan>,

Can you please confirm the exact URL you are seeing CORS issues with. It would also be good if you could modify the issue to follow the provided template for new issues available here: https://github.com/LearningLocker/learninglocker/issues/new

-

**Comment by moneyhan** [comment] 2017-10-23 11:37
**Version**
V2_02

**Steps to reproduce the bug**
1. Launch url: http://webhostqahttp://webhostqa.dignityhealth.org/elearning/launch.html?val=UE1BRDM=

2. Fill Out Form:

    First Name
    Last Name
    Email Address

3.  Click Submit
     Passes Launch URL that includes:
     
      Path to HTML 5 content
      LL EndPoint
      Basic Auth encoded 
      Activity ID for course

**Expected Behavior**

Course Launches and Statements begin recording in LL 

**Actual behavior**

With Fire Fox Web Console Open:

1.  See 2 OPTIONS calls that both generate 407 error code
2.  See 1 OPTION call that receives 200 code.
3.  Loading stops

**Additional information**
OS: LL on Ubuntu 16.04

Browser: Firefox, Chrome and IE 11.  Not sure what versions FireFox and Chrome are.  Don’t have access to them right now.

**Comment by moneyhan** [comment] 2017-10-23 11:39
Launch url won’t be accessible to you I believe.

LL install was done with your latest install script on the Learning Locker Install Page.  Solution using LetsEncrypt cert for SSL

**Comment by ht2** [comment] 2017-10-24 12:48
Hi @moneyhan - what we really need is details about the exact request that is failing. I can't tell from this which part of the API it is hitting, with which query parameters, which headers etc

**Comment by moneyhan** [comment] 2017-10-24 13:18
Do you have some identifying info that I can use to search my Learning Locker log files?

Thanks
Mike

________________________________
On: 24 October 2017 08:48, "James Mullaney" <notifications@github.com<mailto:notifications@github.com>> wrote:

Dignityhealth.org made the following annotations
---------------------------------------------------------------------
STOP, THINK, READ. This is an external email. Exercise extra caution responding to it, opening attachments and following links.
---------------------------------------------------------------------

Hi @moneyhan<https://github.com/moneyhan> - what we really need is details about the exact request that is failing. I can't tell from this which part of the API it is hitting, with which query parameters, which headers etc

-

**Comment by ht2** [comment] 2017-10-24 13:26
This won't be in your log, you would be able to get all that info out of the Network requests in your Firefox Web Console

**Comment by moneyhan** [comment] 2017-10-24 13:28
So I go to the page where the forwarder is setup and then display the web console and look at the Network section?  I didn’t think I would see anything actually running there except maybe when I click submit to create the forwarder.  Is that when I should see the error?

________________________________
On: 24 October 2017 09:26, "James Mullaney" <notifications@github.com<mailto:notifications@github.com>> wrote:

Dignityhealth.org made the following annotations
---------------------------------------------------------------------
STOP, THINK, READ. This is an external email. Exercise extra caution responding to it, opening attachments and following links.
---------------------------------------------------------------------

This won't be in your log, you would be able to get all that info out of the Network requests in your Firefox Web Console

**Comment by ht2** [comment] 2017-10-24 14:00
The forwarder? Sorry I'm lost - what has Statement Forwarding got to do with this?

**Comment by moneyhan** [comment] 2017-10-24 14:12
I’m sorry James.  I have a couple of different things going on.  Was mixing up this one with another one.

Now I am confused.  I reported what I was seeing in the network monitor in the ticket.  I got a 407 authentication required error with back to back OPTION calls.

Are you asking about the requested and response header info?




On: 24 October 2017 10:00, "James Mullaney" <notifications@github.com<mailto:notifications@github.com>> wrote:

Dignityhealth.org made the following annotations
---------------------------------------------------------------------
STOP, THINK, READ. This is an external email. Exercise extra caution responding to it, opening attachments and following links.
---------------------------------------------------------------------

The forwarder? Sorry I'm lost - what has Statement Forwarding got to do with this?

**Comment by ht2** [comment] 2017-10-24 14:16
You reported 407s, but you have no details as to which URL (`data/xAPI` is not enough). Ideally we need to see information about the full request, including what headers were sent with the reqeust, what query parameters were sent, what HTTP method was used.

If you recreate this problem in Chrome, you can right click on the failed request and download a HAR file, which would contain all this information, but without all this information we just can't recreate the problem.

**Comment by moneyhan** [comment] 2017-10-24 14:21
Ok thanks.  At the Learning 2017 conference right now so I will provide the info later this evening when I get to my hotel room.

Thanks again.
Mike

________________________________
On: 24 October 2017 10:16, "James Mullaney" <notifications@github.com<mailto:notifications@github.com>> wrote:

Dignityhealth.org made the following annotations
---------------------------------------------------------------------
STOP, THINK, READ. This is an external email. Exercise extra caution responding to it, opening attachments and following links.
---------------------------------------------------------------------

You reported 407s, but you have no details as to which URL (data/xAPI is not enough). Ideally we need to see information about the full request, including what headers were sent with the reqeust, what query parameters were sent, what HTTP method was used.

If you recreate this problem in Chrome, you can right click on the failed request and download a HAR file, which would contain all this information, but without all this information we just can't recreate the problem.

-

**Comment by ht2** [comment] 2017-10-24 14:50
No problem! Look out for our CEO Ben Betts, he's there too :)

**Comment by moneyhan** [comment] 2017-10-24 14:54
Thanks.  I heard you guys were here just have not been able to run into anyone yet.  Will keep looking though.

________________________________
On: 24 October 2017 10:50, "James Mullaney" <notifications@github.com<mailto:notifications@github.com>> wrote:

Dignityhealth.org made the following annotations
---------------------------------------------------------------------
STOP, THINK, READ. This is an external email. Exercise extra caution responding to it, opening attachments and following links.
---------------------------------------------------------------------

No problem! Look out for our CEO Ben Betts, he's there too :)

-

**Comment by moneyhan** [comment] 2017-10-25 05:42
Here is the har file you asked for.

Michael Monahan
Director, Learning Management
Human Resources

Dignity Health
480.535.4836 (Work)
480.773.1390 (Cell)
602.798.9517 (Fax)

For MyJourney Issues or Requests, please open an IT Helpdesk Ticket using one of the two methods shown below.  This is the best method to get help.

Helpdesk Phone: (888) 307-0222
Online Request Form: MyJourney Help Request<https://edc-adfs-lb.chw.edu/adfs/ls/idpinitiatedsignon.aspx?RelayState=RPID%3Dhttps%253A%252F%252Fdignityhealth.csod.com%26RelayState%3D%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253d39>

Caution: This email is both proprietary and confidential, and not intended for transmission to or receipt by any unauthorized
persons. If you believe that it has been received by you in error, do not read any attachments. Instead, kindly reply to the
sender stating that you have received the message in error. Then destroy it and any attachments. Thank you.

**Comment by ht2** [comment] 2017-10-26 07:38
Hi @moneyhan, I think you may have attached a file to an email, which is not going to work with Github Issues; you will need to provide a download link to the file or upload it directly to the ticket here: https://github.com/LearningLocker/learninglocker/issues/1004

**Comment by moneyhan** [comment] 2017-10-26 15:06
Would not let me add a har file.  Here is the actual data from it

**Comment by moneyhan** [comment] 2017-10-26 15:07
[webhostqa.dignityhealth.org-1508883842937.log](https://github.com/LearningLocker/learninglocker/files/1418908/webhostqa.dignityhealth.org-1508883842937.log)

**Comment by moneyhan** [comment] 2017-10-26 15:10
Loaded it with a .log file extention instead.  It is a Har file though.

**Comment by moneyhan** [comment] 2017-10-26 15:13
[webhostqa.dignityhealth.org-1508883842937.txt](https://github.com/LearningLocker/learninglocker/files/1418934/webhostqa.dignityhealth.org-1508883842937.txt)

**Comment by moneyhan** [comment] 2017-10-26 15:13
Would not let me attach as a HAR file so renamed to txt.  Is still a Har file though.  Thanks.

**Comment by ht2** [comment] 2017-10-26 15:21
Just had a look in it and it doesn't look like a HAR, its got a bunch of Javascript debugging in it.

Just to check, you right clicked the network requests in Chrome and selected this right:

![image](https://user-images.githubusercontent.com/1352590/32061520-c02b3f22-ba69-11e7-99e9-6d111672e0e1.png)

**Comment by moneyhan** [comment] 2017-10-26 15:24
That is what I did.  This is the file that produced.  I had to change the extension to .txt though because the site would not let me upload it with a .har extension.

Michael Monahan
Director, Learning Management
Human Resources

Dignity Health
480.535.4836 (Work)
480.773.1390 (Cell)
602.798.9517 (Fax)

For MyJourney Issues or Requests, please open an IT Helpdesk Ticket using one of the two methods shown below.  This is the best method to get help.

Helpdesk Phone: (888) 307-0222
Online Request Form: MyJourney Help Request<https://edc-adfs-lb.chw.edu/adfs/ls/idpinitiatedsignon.aspx?RelayState=RPID%3Dhttps%253A%252F%252Fdignityhealth.csod.com%26RelayState%3D%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253d39>

Caution: This email is both proprietary and confidential, and not intended for transmission to or receipt by any unauthorized
persons. If you believe that it has been received by you in error, do not read any attachments. Instead, kindly reply to the
sender stating that you have received the message in error. Then destroy it and any attachments. Thank you.

**Comment by moneyhan** [comment] 2017-10-26 15:27
Are you looking at the one with the .log extension.  I deleted that one (or so I thought) right after I sent because I realized it was the wrong file.  Uploaded a second file with a .txt extension.

Michael Monahan
Director, Learning Management
Human Resources

Dignity Health
480.535.4836 (Work)
480.773.1390 (Cell)
602.798.9517 (Fax)

For MyJourney Issues or Requests, please open an IT Helpdesk Ticket using one of the two methods shown below.  This is the best method to get help.

Helpdesk Phone: (888) 307-0222
Online Request Form: MyJourney Help Request<https://edc-adfs-lb.chw.edu/adfs/ls/idpinitiatedsignon.aspx?RelayState=RPID%3Dhttps%253A%252F%252Fdignityhealth.csod.com%26RelayState%3D%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253d39>

Caution: This email is both proprietary and confidential, and not intended for transmission to or receipt by any unauthorized
persons. If you believe that it has been received by you in error, do not read any attachments. Instead, kindly reply to the
sender stating that you have received the message in error. Then destroy it and any attachments. Thank you.

**Comment by ht2** [comment] 2017-10-27 08:49
Hey @moneyhan - sorry if I am being dumb, but I can only see this file (in this comment): https://github.com/LearningLocker/learninglocker/issues/1004#issuecomment-339698914

...and that defintely isn't a HAR. So I think things have got muddled

**Comment by moneyhan** [comment] 2017-10-27 14:12
Strange.  It looked like it saved the file when I added it but now I don't see it.  Will try again shortly.

**Comment by moneyhan** [comment] 2017-10-27 14:43
[webhostqa.dignityhealth.org.txt](https://github.com/LearningLocker/learninglocker/files/1422410/webhostqa.dignityhealth.org.txt)

**Comment by moneyhan** [comment] 2017-10-27 14:43
Hopefully it took this time.  Here is a screen shot of it loaded in my comment.

**Comment by moneyhan** [comment] 2017-10-27 14:44
![2017-10-27_7-43-12](https://user-images.githubusercontent.com/31706731/32109807-9a6929c6-baea-11e7-8839-7f2506da6075.jpg)

**Comment by ht2** [comment] 2017-10-27 14:52
Haha, ok this time the file is cut off if you open it! If you open the file in an editor, like notepad or Sublime Text, do you see that the end of it is cut off (e.g. unfinished JSON). It could just be that Github is doing this.

**Comment by moneyhan** [comment] 2017-10-27 14:54
Do you want to send an email to Michael.monahan@dignityhealth.org<mailto:Michael.monahan@dignityhealth.org> and I will reply to you with the file.  We can take github out of the picture.

Michael Monahan
Director, Learning Management
Human Resources

Dignity Health
480.535.4836 (Work)
480.773.1390 (Cell)
602.798.9517 (Fax)

For MyJourney Issues or Requests, please open an IT Helpdesk Ticket using one of the two methods shown below.  This is the best method to get help.

Helpdesk Phone: (888) 307-0222
Online Request Form: MyJourney Help Request<https://edc-adfs-lb.chw.edu/adfs/ls/idpinitiatedsignon.aspx?RelayState=RPID%3Dhttps%253A%252F%252Fdignityhealth.csod.com%26RelayState%3D%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253d39>

Caution: This email is both proprietary and confidential, and not intended for transmission to or receipt by any unauthorized
persons. If you believe that it has been received by you in error, do not read any attachments. Instead, kindly reply to the
sender stating that you have received the message in error. Then destroy it and any attachments. Thank you.

**Comment by moneyhan** [comment] 2017-10-27 14:58
Also, are you changing the extension back to .har from .txt.  When I open from the file I loaded it goes to like 1391.  Last line shown in the attached image.

**Comment by ht2** [comment] 2017-10-27 15:37
OK, that worked and we can see the request.

On inspection, I believe this is behaving exactly as required - there are 3 request to CORS made by the browser, with the last one being a `200 connection established`. 

![image](https://user-images.githubusercontent.com/1352590/32112270-b4dcb5a8-bb34-11e7-8233-a95f7dc053e1.png)

![image](https://user-images.githubusercontent.com/1352590/32112284-bcd57902-bb34-11e7-9752-30e6d664c4b9.png)

I think the 407 is just a process to an end. You can see in the 2nd request a `Proxy-Authorization` header is added to the Request headers, and on the final request (where we see the 200) it sends a even more complete version of the `Proxy-Authorization` header.

We're using the [npm CORS](https://www.npmjs.com/package/cors) library to handle all of this. Now I'm not expect in CORS to be honest, but as far as I can see this is all working exactly as intended.

So I guess the question is, other than seeing that there is a 407 in your network panel for the OPTIONS to /data/xAPI/state (which is followed by a 200), have you actually seen a State request _fail_?

**Comment by moneyhan** [comment] 2017-10-27 15:51
Basically what should happen is that you should keep seeing messages as the course plays.  Should be seeing PUT statements, etc. as it writes statements to the LRS.  None of that is happening.  When I change the end point to my SCORM Cloud LRS (all other factors being exactly the same) the same course functions perfectly.  It seems to be getting hung up after that last 200 message.  Does not write the very first message to LRS indicating user has attempted the course.

Michael Monahan
Director, Learning Management
Human Resources

Dignity Health
480.535.4836 (Work)
480.773.1390 (Cell)
602.798.9517 (Fax)

For MyJourney Issues or Requests, please open an IT Helpdesk Ticket using one of the two methods shown below.  This is the best method to get help.

Helpdesk Phone: (888) 307-0222
Online Request Form: MyJourney Help Request<https://edc-adfs-lb.chw.edu/adfs/ls/idpinitiatedsignon.aspx?RelayState=RPID%3Dhttps%253A%252F%252Fdignityhealth.csod.com%26RelayState%3D%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253d39>

Caution: This email is both proprietary and confidential, and not intended for transmission to or receipt by any unauthorized
persons. If you believe that it has been received by you in error, do not read any attachments. Instead, kindly reply to the
sender stating that you have received the message in error. Then destroy it and any attachments. Thank you.

**Comment by moneyhan** [comment] 2017-10-27 15:52
I will send you another file where it is working so you can see all of the additional activity.

Michael Monahan
Director, Learning Management
Human Resources

Dignity Health
480.535.4836 (Work)
480.773.1390 (Cell)
602.798.9517 (Fax)

For MyJourney Issues or Requests, please open an IT Helpdesk Ticket using one of the two methods shown below.  This is the best method to get help.

Helpdesk Phone: (888) 307-0222
Online Request Form: MyJourney Help Request<https://edc-adfs-lb.chw.edu/adfs/ls/idpinitiatedsignon.aspx?RelayState=RPID%3Dhttps%253A%252F%252Fdignityhealth.csod.com%26RelayState%3D%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253d39>

Caution: This email is both proprietary and confidential, and not intended for transmission to or receipt by any unauthorized
persons. If you believe that it has been received by you in error, do not read any attachments. Instead, kindly reply to the
sender stating that you have received the message in error. Then destroy it and any attachments. Thank you.

**Comment by ht2** [comment] 2017-10-31 15:39
Closing - was discovered that the XAPI_PORT was not set in the nginx config.

**Closed by ht2** 2017-10-31 15:39 UTC
