### ISSUE TITLE
Exception: aggregation result exceeds maximum document size (16MB)

### ISSUE THREAD

**Issue by andrewdisney** [LearningLocker/learninglocker#782] opened 2016-02-22 15:17 UTC
We just went live with a website that uses learning locker. There are currently about 450,000 statements after 1 week of use.

We can no longer load the learning locker website or call the aggregate API cause we get this error:

exception: aggregation result exceeds maximum document size (16MB)

What solutions have people come up with to larger data sets of statements? Are we missing a mongodb config? We are running version 1.9 cause we have not had a chance to upgrade. Does version 1.11 have this problem?

**Comment by hallshouse** [comment] 2016-02-22 15:24
Hey Andrew:
What is your PHP setting for the max_post_size?
How much resources does your server have?
Memory
CPU
HDD
etc..

**Comment by andrewdisney** [comment] 2016-02-22 15:27
The max_post_size is 128mb. That is not what the query is exceeding. It is exceeding the BSON document size in mongodb. I will get you server stats soon.

**Comment by hallshouse** [comment] 2016-02-22 15:35
No need for the server info now.
In MongoDB, the BSON document size limit is 16MB. This is not a LL configuration and is not changed via any config file.
Here is a good reference: https://jira.mongodb.org/browse/SERVER-431

MongoDB is supposed to break a document that is too large into chunks to avoid this.
What version of MongoDB are you running?

**Comment by ryansmith94** [comment] 2016-02-22 15:37
This is most likely caused by #760 @andrewdisney

**Comment by ht2** [comment] 2016-02-22 15:40
@andrewdisney What is the exact route throwing the expception? Is this as a result of a query to the aggregation API you are running?

**Comment by andrewdisney** [comment] 2016-02-22 15:47
It is both. We get it on the homepage after logging in and we are doing an API call /api/v1/statements/aggregate

**Comment by ht2** [comment] 2016-02-22 15:53
OK, and what version are you running?

**Comment by andrewdisney** [comment] 2016-02-22 15:53
1.9. We currently are working on upgrading.

**Comment by andrewdisney** [comment] 2016-02-22 15:54
Mongo 2.6

**Comment by ht2** [comment] 2016-02-22 15:57
Certainly there are massive permormance increases in v1.11 (and especially in the current develop branch and issue/slow-counts which I hope to get merged in soon). I would strongly recommend getting up to at least v1.11 ASAP and seeing if that helps. The problem is simply that too much data is trying to be piped out of the aggregation API. _You_ can control that with your API requests by ensuring you only query and pipe parts of the statement you actually need. Out of interest do you have a rough idea of the size of one of your average statements? We typically see about 3-5kb and haven't hit document limits with LRSs with millions of statements.

**Comment by andrewdisney** [comment] 2016-02-22 16:03
They are not large at all. Here is the last one we got a few seconds ago:

> {
    "version": "1.0.0",
    "actor": {
        "objectType": "Agent",
        "name": "\u5b59\u590f\u4e1c",
        "account": {
            "name": "sunxiadong",
            "homePage": "https://lms.shanghaidisneyresort.com"
        }
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/completed",
        "display": {
            "en-US": "completed",
            "en-GB": "completed"
        }
    },
    "result": {
        "score": {
            "scaled": 1,
            "raw": 1
        },
        "success": true,
        "completion": true
    },
    "context": {
        "contextActivities": {
            "parent": [
                {
                    "objectType": "Activity",
                    "id": "https://lms.shanghaidisneyresort.com/course/view.php?id=12"
                }
            ]
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "https://lms.shanghaidisneyresort.com/mod/quiz/attempt.php?attempt=5235&page=0",
        "definition": {
            "name": {
                "en-US": "What should we do to be \u201cconsumer-centric\u201d?",
                "en-GB": "What should we do to be \u201cconsumer-centric\u201d?"
            },
            "description": {
                "en-US": "<p>\u4ee5\u6d88\u8d39\u8005\u4e3a\u6838\u5fc3\u9700\u8981\u505a\u5230\uff1a<br></p>",
                "en-GB": "<p>\u4ee5\u6d88\u8d39\u8005\u4e3a\u6838\u5fc3\u9700\u8981\u505a\u5230\uff1a<br></p>"
            }
        }
    },
    "authority": {
        "objectType": "Agent",
        "name": "SHDR",
        "mbox": "mailto:devteam@simple.dtadev.com"
    },
    "stored": "2016-02-22T15:59:58.821900+00:00",
    "timestamp": "2016-02-22T15:59:58.821900+00:00",
    "id": "1efad2a1-aac7-472c-8ab9-8a29b7184117"
}

**Comment by ht2** [comment] 2016-02-22 16:06
Yeah that looks pretty lightweight, we've seen much larger so that is odd. I would suggest looking into profiling mongo and diving into the slow query logs to get an idea what exactly is failing. I would also strongly recommend moves to Mongo 3.* where possible, and as before upgrade your LL if you can.

**Comment by ryansmith94** [comment] 2016-02-23 17:52
This is probably be fixed by 1.12.0 @andrewdisney if it wasn't already.

**Comment by andrewdisney** [comment] 2016-02-24 14:26
We tried to upgrade to 1.11 earlier this week. We messed up the upgrade and had to rollback. We are still running version 1.9. We are almost up to 400,000 statements. We are going to try and upgrade to 1.12 today.

We changed our API call to limit to 1000 statements at a time. That is now timing out. See error response below:

`{"error":true,"success":false,"message":"10.132.117.20:27017: Read timed out after reading 0 bytes, waited for 30.000000 seconds","code":500,"trace":[{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/app\/locker\/repository\/Query\/EloquentQueryRepository.php","line":89,"function":"aggregate","class":"MongoCollection","type":"->","args":[[{"$match":{"$and":[{"statement.timestamp":{"$gt":"2016-02-23T14:06:08 0800","$lt":"2100-01-01T00:00:00 0800"},"voided":false},{"lrs_id":{"$id":"564b53bd62dae9b95e4b1589"},"active":true}]}},{"$project":{"_id":0,"statement":1}},{"$sort":{"statement.timestamp":1}},{"$limit":1000}]]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/app\/locker\/repository\/Query\/EloquentQueryRepository.php","line":94,"function":"Locker\\Repository\\Query\\{closure}","class":"Locker\\Repository\\Query\\EloquentQueryRepository","type":"->","args":[]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/app\/controllers\/api\/Statements.php","line":33,"function":"aggregate","class":"Locker\\Repository\\Query\\EloquentQueryRepository","type":"->","args":[{"lrs_id":{"$id":"564b53bd62dae9b95e4b1589"},"scopes":["all"],"client":{"_id":"564b53bd62dae9b95e4b158a","api":{"basic_key":"","basic_secret":""},"lrs_id":"564b53bd62dae9b95e4b1589","authority":{"name":"SHDR","mbox":"mailto:devteam@simple.dtadev.com"},"scopes":["all"],"updated_at":"2015-11-25 17:21:42","created_at":"2015-11-17 16:20:13"}},[{"$match":{"statement.timestamp":{"$gt":"2016-02-23T14:06:08 0800","$lt":"2100-01-01T00:00:00 0800"},"voided":false}},{"$project":{"_id":0,"statement":1}},{"$sort":{"statement.timestamp":1}},{"$limit":1000}]]},{"function":"aggregate","class":"Controllers\\API\\Statements","type":"->","args":[]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php","line":231,"function":"call_user_func_array","args":[[{"lrs":{"_id":"564b53bd62dae9b95e4b1589","title":"SHDR Production","description":"This is the locker for SHDR production enviroment","owner_id":"560d8cea03142ab164e9d3ed","users":[{"_id":"560d8cea03142ab164e9d3ed","email":"devteam@simple.dtadev.com","name":"admin","role":"admin"}],"updated_at":"2015-11-17 16:20:13","created_at":"2015-11-17 16:20:13"},"client":{"_id":"564b53bd62dae9b95e4b158a","api":{"basic_key":"","basic_secret":""},"lrs_id":"564b53bd62dae9b95e4b1589","authority":{"name":"SHDR","mbox":"mailto:devteam@simple.dtadev.com"},"scopes":["all"],"updated_at":"2015-11-25 17:21:42","created_at":"2015-11-17 16:20:13"}},"aggregate"],[]]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php","line":93,"function":"callAction","class":"Illuminate\\Routing\\Controller","type":"->","args":["aggregate",[]]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php","line":62,"function":"call","class":"Illuminate\\Routing\\ControllerDispatcher","type":"->","args":[{"lrs":{"_id":"564b53bd62dae9b95e4b1589","title":"SHDR Production","description":"This is the locker for SHDR production enviroment","owner_id":"560d8cea03142ab164e9d3ed","users":[{"_id":"560d8cea03142ab164e9d3ed","email":"devteam@simple.dtadev.com","name":"admin","role":"admin"}],"updated_at":"2015-11-17 16:20:13","created_at":"2015-11-17 16:20:13"},"client":{"_id":"564b53bd62dae9b95e4b158a","api":{"basic_key":"","basic_secret":""},"lrs_id":"564b53bd62dae9b95e4b1589","authority":{"name":"SHDR","mbox":"mailto:devteam@simple.dtadev.com"},"scopes":["all"],"updated_at":"2015-11-25 17:21:42","created_at":"2015-11-17 16:20:13"}},{},"aggregate"]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":962,"function":"dispatch","class":"Illuminate\\Routing\\ControllerDispatcher","type":"->","args":[{},{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},"Controllers\\API\\Statements","aggregate"]},{"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Router","type":"->","args":[]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php","line":109,"function":"call_user_func_array","args":[{},[]]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":1028,"function":"run","class":"Illuminate\\Routing\\Route","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":996,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":776,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":746,"function":"dispatch","class":"Illuminate\\Foundation\\Application","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php","line":72,"function":"handle","class":"Illuminate\\Foundation\\Application","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php","line":47,"function":"handle","class":"Illuminate\\Session\\Middleware","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php","line":51,"function":"handle","class":"Illuminate\\Cookie\\Queue","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php","line":23,"function":"handle","class":"Illuminate\\Cookie\\Guard","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":642,"function":"handle","class":"Stack\\StackedHttpKernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/usr\/local\/zend\/var\/apps\/http\/lrs.shanghaidisneyresort.com\/80\/1.7_276\/public\/index.php","line":49,"function":"run","class":"Illuminate\\Foundation\\Application","type":"->","args":[]}]}`

**Comment by ht2** [comment] 2016-02-24 14:41
[The insert/update problem](https://github.com/LearningLocker/learninglocker/pull/781) is also addressed in the 1.12 release.

What went wrong with the migration may I ask?

**Comment by andrewdisney** [comment] 2016-02-24 14:48
The storage directory configuration was overwritten. Our bad.

**Comment by ht2** [comment] 2016-02-24 14:50
Ok, good luck with today's attempt!

**Comment by andrewdisney** [comment] 2016-02-24 20:12
We were able to upgrade to V 1.12. That fixed home page issue. This app is used in China so we will have to wait for peak use time (which is 2pm China time) to confirm that the API is working at all times.

**Comment by ryansmith94** [comment] 2016-02-24 21:01
Good to hear @andrewdisney :) Keep us posted :+1:

**Comment by andrewdisney** [comment] 2016-02-25 15:07
The site was able to handle peak time yesterday! We now have 831,890 statements. We are averaging 100,000 statements a day now.

Thanks for your help!

**Comment by ryansmith94** [comment] 2016-02-26 08:24
That's awesome! :smile: no worries, thanks for keeping us posted.

**Comment by ht2** [comment] 2016-03-01 10:11
Going to close this out as it looks like the recent updates have helped

**Closed by ht2** 2016-03-01 10:11 UTC
Labels: priority:high, status:confirmed, type:bug
