### ISSUE TITLE
uploads/{lrs_id}/documents dir over 3G with over 700K files

### ISSUE THREAD

**Issue by bullandrock** [LearningLocker/learninglocker#811] opened 2016-05-02 20:23 UTC
**Version**
1.12.0

We noticed the {storage} /uploads/{lrs_id}/documents has over 700K files using up 3G of disk space.
…
-rw-r--r-- 1 apache apache  480 Apr 25 15:52 1461617540_943.bin
-rw-r--r-- 1 apache apache    7 Apr 25 15:52 1461617541_219.bin
-rw-r--r-- 1 apache apache  480 Apr 25 15:52 1461617541_884.bin
-rw-r--r-- 1 apache apache    8 Apr 25 15:52 1461617543_135.bin
-rw-r--r-- 1 apache apache  527 Apr 25 15:52 1461617543_422.bin
-rw-r--r-- 1 apache apache   20 Apr 25 15:52 1461617544_139.bin
-rw-r--r-- 1 apache apache  833 Apr 25 15:52 1461617544_586.bin
-rw-r--r-- 1 apache apache    8 Apr 25 15:52 1461617544_707.bin
-rw-r--r-- 1 apache apache  509 Apr 25 15:52 1461617545_210.bin
-rw-r--r-- 1 apache apache    7 Apr 25 15:52 1461617548_405.bin
…

Our site has gone live a few weeks ago and the files were generated in that time.

I am thinking the code that generated these files is app/models/DocumentAPI.php since it references the directory “documents”.

Can someone please pass information on how to handle these files? Whether they can be deleted or at what age can they be deleted.

**Comment by ht2** [comment] 2016-05-03 08:20
These files are storage for the [Document API](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#miscdocument) part of the xAPI application, which provides binary (and data) storage for activity providers. Therefore, one of your linked applications must be utilising the Document API for storage.

**Comment by ht2** [comment] 2016-05-03 08:30
Regarding whether they can be deleted, assuming your activity provider expects them to be there, no they can not. You should be looking into utilising cheap cloud storage facilities such as Amazon's S3 or Rackspace's Cloud Files. LL is configured to use [PHP Flysystem](http://flysystem.thephpleague.com/) for file storage, allowing for different file storage solutions. 

You can read all about the different configurations [here](https://github.com/LearningLocker/learninglocker/tree/develop/app/locker/repository/File).

**Comment by ht2** [comment] 2016-05-09 14:47
I'm going to close this issue off as the behaviour is expected and is caused by an Activity Provider sending binary files to the Document API

**Closed by ht2** 2016-05-09 14:47 UTC
Labels: priority:low, status:confirmed, type:question

**Comment by andrewdisney** [comment] 2016-08-26 14:41
We have courses made in Story Line and Articulate creating these files at a rapid pace. The files seem to be created for almost every statement. When we look in the files, they are only one line with a bookmark of where the user is in that course.

We are using Rackspace Cloud Files for these. However based on current usage we will have a few million of these files generated every few months. If we delete all documents older than 30 days, will learning locker throw errors? We are pretty sure the courses don't care about these files.

Thanks for answering our question.

**Comment by ht2** [comment] 2016-08-26 16:41
You can delete these, but if you use content that requires the files then that content might not work. Hosting an LRS requires taking on responsibility for hosting data and binary storage. I would not expect errors to be thrown, but if you are doing it properly then you should probably delete the respective database entries for the documents as well. If errors are thrown, it would only be if those documents are requested.

**Comment by hallshouse** [comment] 2016-08-26 16:54
Be aware, deleting statements will also effect your reporting output. If you really need to delete statements (which I would never do in production) you will be throwing out any valid reporting data that requires a more statistical approach to be accurate.

As well, before drop any statements, be sure you have backed up your DB and have also created reports to collect all data that will be dropped. At least you will then still have an audit trail.

**Comment by andrewdisney** [comment] 2016-08-26 17:49
Sounds good. We might look for a way to remove references to files in the statements as we delete files. Since the courses are not doing a good job of deleting files. We will figure out a automatic way to do it. The building of millions of files that are not good for anything is not sustainable.
