### ISSUE TITLE
Got 2 problemes, file_get_contents() & send statements

### ISSUE THREAD

**Issue by Lupei** [LearningLocker/learninglocker#638] opened 2015-05-21 12:40 UTC
Hi guys i got a probleme, i use a personal LMS with LL (LRS) since 2 weeks and it worked week. Today (21/05/2015) when i go to LL (LRS) i got this error : Status: 500 Error: file_get_contents(): (View: C:\xampp\htdocs\umihf_uk\tincan_lrs\app\views\layouts\sidebars\sidebar_footer.blade.php) (View: C:\xampp\htdocs\umihf_uk\tincan_lrs\app\views\layouts\sidebars\sidebar_footer.blade.php) (View: C:\xampp\htdocs\umihf_uk\tincan_lrs\app\views\layouts\sidebars\sidebar_footer.blade.php).

And my courses don't work anymore. When i check firebug i got this : 
- 404 error / POST / message "Could not find state with id `resume`".

Thanks.

**Comment by ryansmith94** [comment] 2015-05-21 12:45
Duplicate of #635

**Closed by ryansmith94** 2015-05-21 12:45 UTC

**Comment by Lupei** [comment] 2015-05-21 12:56
Thanks for the anwser.

Ok to my first error : file_get_contents() but what about the second ?

Missed this : 
- In firebug : 500 / POST / message : Call to a member function setTimezone() on a non-object

Thanks.

**Comment by ryansmith94** [comment] 2015-05-21 15:17
Ok, please create a issue specific to your unresolved issue using our [bug template](https://github.com/LearningLocker/learninglocker/blob/develop/contributing.md).
