### ISSUE TITLE
LRS statements are not shown after dumping and restoring mongo database

### ISSUE THREAD

**Issue by salexfo** [LearningLocker/learninglocker#742] opened 2015-09-17 14:23 UTC
Hi,
I wanted to export and import a learning locker db from one installation to another. 
Export from an Ubuntu server that has v1.8 installed and import to a centos server that has v1.10 installed.

All went well except for the fact that when I open the application to which the database has been exported I do see all the statements on the admin dashboard but see 0 statements inside the LRS.
(See attached)

Any help will be much appreciated.
![selection_459](https://cloud.githubusercontent.com/assets/8767588/9935686/b9da6098-5d60-11e5-844c-384363edf9c9.png)
![selection_458](https://cloud.githubusercontent.com/assets/8767588/9935687/b9dcb51e-5d60-11e5-857e-b39b46c8173d.png)

**Comment by daniel-abbey** [comment] 2015-09-17 14:46
Hi @salexfo,
Thanks for getting in touch.
When you installed 1.10.0, did you follow the [installation instructions](http://docs.learninglocker.net/installation/#setup-mongodb)? We are now required to create our own app/config/local/database.php files - can you confirm that this step was performed?

**Comment by salexfo** [comment] 2015-09-17 14:52
Confirmed. I have created and updated the file at app/config/local/database.php

**Comment by daniel-abbey** [comment] 2015-09-17 14:59
If you click Statements on the left menu, does it show the statements? or is it just the statement count?

**Comment by salexfo** [comment] 2015-09-17 15:01
@daniel-abbey 
That's what I get when I click on "statements" 
![selection_460](https://cloud.githubusercontent.com/assets/8767588/9936721/0f2e3786-5d66-11e5-88db-88e49a774e10.png)

**Comment by daniel-abbey** [comment] 2015-09-17 15:04
and you ran `php artisan migrate`?

**Comment by salexfo** [comment] 2015-09-17 15:05
@daniel-abbey 
What for?
It's a db dump, there are no migration files or am I missing something?

**Comment by daniel-abbey** [comment] 2015-09-17 15:13
My bad.
It is strange that they show up in the admin dashboard but not the LRS dashboard.
Can you confirm that the admin user is a member of the LRS. Admin Dashboard -> Users -> LRSs column

**Comment by salexfo** [comment] 2015-09-17 15:19
@daniel-abbey 
That's strange. When I'm inside the LRS and click on "Manage Users" I see my user but when I go via
Admin Dashboard -> Users -> LRSs that's what I get:
![selection_461](https://cloud.githubusercontent.com/assets/8767588/9937253/95c97bd2-5d68-11e5-84da-d6e0dc4295c8.png)

**Comment by daniel-abbey** [comment] 2015-09-17 15:27
It appears there are no LRSs associated with the newly created user. Did you create a new user after the new installation? If so, even though their email and password credentials are identical to those used on your previous installation, the user will have a new unique ID, which won't match the `db.lrs.users._id` found in the database.

**Comment by hallshouse** [comment] 2015-09-17 15:38
FYI: This is the same (exact) symptom you get when your do not have the correct permissions on the LL sub folders. Check your permissions on the 1.10 server.

**Comment by salexfo** [comment] 2015-09-17 15:39
@hallshouse 
I have 775 permissions on folders and 664  on files.
The group of the files is set to nginx

**Comment by salexfo** [comment] 2015-09-17 15:56
@daniel-abbey 
I didn't create a new user

**Comment by daniel-abbey** [comment] 2015-09-17 15:57
I will look into this and try to reproduce the issue tomorrow.

**Comment by salexfo** [comment] 2015-09-17 15:58
@daniel-abbey 
Thanks a lot for your help

**Comment by pondermatic** [comment] 2015-09-17 19:00
This issue sounds like a result of the MongoId issues that I have been fixing. Learning Locker v1.8.0 used `jenssegers/mongodb` v1.4.x. Learning Locker v1.9+ uses `jenssegers/mongodb` 2.0.x, which expects foreign ids based on `_id` to be MongoIds instead of stings.

**Comment by salexfo** [comment] 2015-09-20 08:36
Hi,
Is it possible to manually add the user as the owner of the LRS?

**Comment by daniel-abbey** [comment] 2015-09-21 11:24
Hi @salexfo,
Yes it is possible by changing the `db.lrs.owner_id` in the database.

**Comment by salexfo** [comment] 2015-09-21 12:17
@daniel-abbey
Hi, I've checked the content of the LRS collection. It's identical to what we have on the original server.

**Comment by daniel-abbey** [comment] 2015-09-21 14:16
Hi @salexfo,
As [@pondermatic suggested](https://github.com/LearningLocker/learninglocker/issues/742#issuecomment-141189754) it's probably due to the MongoIds. This issue will be addressed in the next release of Learning Locker.

**Comment by daniel-abbey** [comment] 2015-09-25 16:04
@salexfo please try upgrading to [v1.11.0](https://github.com/LearningLocker/learninglocker/releases/tag/v1.11.0) and let us know if this solves the issue. Thankyou.

**Comment by salexfo** [comment] 2015-09-27 07:08
Hi @daniel-abbey 
Is it possible to upgrade from 1.10 to 1.11?
I'm getting merge: 1.11.0 - not something we can merge
when entering git merge 1.11.0

**Comment by salexfo** [comment] 2015-09-27 07:22
@daniel-abbey 
Upgraded,
now I get this strange error when I try to access the specific LRS:
![selection_467](https://cloud.githubusercontent.com/assets/8767588/10121695/a10e5c6a-6501-11e5-803d-af7a0e31c456.png)

**Comment by daniel-abbey** [comment] 2015-09-27 07:54
Hi @salexfo, it should be `git merge v1.11.0`. You missed out the 'v'.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.3.5&pv=5.1.1&source=email_footer_2] On Sun, Sep 27, 2015 at 8:08 am, salexfo < notifications@github.com [notifications@github.com] > wrote:
Hi @daniel-abbey [https://github.com/daniel-abbey]
Is it possible to upgrade from 1.10 to 1.11?
I'm getting merge: 1.11.0 - not something we can merge
when entering git merge 1.11.0

—
Reply to this email directly or view it on GitHub
[https://github.com/LearningLocker/learninglocker/issues/742#issuecomment-143526128] .[https://github.com/notifications/beacon/AMhkH7vvldU42_m1eHN7fWUOJPhEG-2Uks5o141egaJpZM4F_Le6.gif]

**Comment by salexfo** [comment] 2015-09-27 07:59
@daniel-abbey,
The merge issue solved. However as you can see now I'm encountering the strange error above

**Comment by hallshouse** [comment] 2015-09-27 13:22
I had this exact symptom after performing the update as well. I had to update mongoDB to the latest build and also found I had to update my Composer Token and get a new one. After all that, I then did a new installation and it all worked fine.

**Comment by salexfo** [comment] 2015-09-28 07:50
@hallshouse 
That's the isValid issue?

**Comment by pondermatic** [comment] 2015-09-28 15:04
@salexfo,
The `Trying to get property of non-object` error you saw in `app/views/partials/lrs/dashboard.blade.php` is probably because the LRS's first client object isn't getting loaded from the database. `LrsController->show()` is the only place that the view is used and it asks `Client->where($lrs_id)->first()` to load the client object.

Either `app/models/Client.php` is not updated to v1.11.0 (see if it has a `where()` function), or perhaps the client foreign ids migration did not run successfully. Try `php artisan migrate --env=local`.

**Comment by daniel-abbey** [comment] 2015-09-29 13:13
@salexfo I also encountered the error in your screenshot on v1.9.0, but this was fixed by merging the checked out branch with the v1.11.0 tag and migrating as per the upgrade procedure. Not sure why every branch should need upgrading but this worked for me.

**Comment by salexfo** [comment] 2015-09-30 09:09
@daniel-abbey 
Thanks. That did the trick.
In addition, the original issue is now solved as well.

**Comment by daniel-abbey** [comment] 2015-09-30 09:14
@salexfo Great to hear! Let us know if your have any more issues.

**Closed** 2015-10-13 12:22 UTC
Labels: priority:medium, status:unconfirmed, type:bug
