### ISSUE TITLE
MongoCursorTimeoutException (80)

### ISSUE THREAD

**Issue by ngarafol** [LearningLocker/learninglocker#814] opened 2016-05-16 07:28 UTC
Dont know if this is duplicate of #764 or not :)

**Version**
master at 627be8f on 1.12.1 

**Steps to reproduce the bug**
1. Login to learning locker URL

**Expected behaviour**
User should login in administration dashboard

**Actual behaviour**
User is presented with MongoCursorTimeoutException error. 

localhost:27017: Read timed out after reading 0 bytes, waited for 30.000000 seconds

**Additional information**
OS: Debian 8 x64
Browser: Chromium Version 50.0.2661.94 (64-bit)
MongoDB version 3.2
php5-mongo module version 1.5.7
Mongo database seems to work, background task emitting records from moodle log to LRS seems to work. 

Stacktrace:

28. MongoCursorTimeoutException
…/­vendor/­jenssegers/­mongodb/­src/­Jenssegers/­Mongodb/­Query/­Builder.php262
27. MongoCursor rewind
<#unknown>0
26. iterator_to_array
…/­vendor/­jenssegers/­mongodb/­src/­Jenssegers/­Mongodb/­Query/­Builder.php262
25. Jenssegers\Mongodb\Query\Builder getFresh
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Query/­Builder.php1384
24. Illuminate\Database\Query\Builder get
…/­vendor/­jenssegers/­mongodb/­src/­Jenssegers/­Mongodb/­Query/­Builder.php126
23. Jenssegers\Mongodb\Query\Builder get
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Query/­Builder.php1369
22. Illuminate\Database\Query\Builder first
…/­app/­locker/­data/­dashboards/­BaseDashboard.php59
21. app\locker\data\dashboards\BaseDashboard statementDays
…/­app/­locker/­data/­dashboards/­BaseDashboard.php84
20. app\locker\data\dashboards\BaseDashboard statementAvgCount
…/­app/­locker/­data/­dashboards/­BaseDashboard.php23
19. app\locker\data\dashboards\BaseDashboard getStats
…/­app/­locker/­data/­dashboards/­AdminDashboard.php17
18. app\locker\data\dashboards\AdminDashboard getFullStats
…/­app/­controllers/­SiteController.php40
17. SiteController index
<#unknown>0
16. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Controller.php231
15. Illuminate\Routing\Controller callAction
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php93
14. Illuminate\Routing\ControllerDispatcher call
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php62
13. Illuminate\Routing\ControllerDispatcher dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php967
12. Illuminate\Routing\Router Illuminate\Routing\{closure}
<#unknown>0
11. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php109
10. Illuminate\Routing\Route run
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1033
9. Illuminate\Routing\Router dispatchToRoute
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1001
8. Illuminate\Routing\Router dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php775
7. Illuminate\Foundation\Application dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php745
6. Illuminate\Foundation\Application handle
…/­vendor/­itsgoingd/­clockwork/­Clockwork/­Support/­Laravel/­ClockworkLegacyMiddleware.php20
5. Clockwork\Support\Laravel\ClockworkLegacyMiddleware handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Session/­Middleware.php72
4. Illuminate\Session\Middleware handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Queue.php47
3. Illuminate\Cookie\Queue handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Guard.php51
2. Illuminate\Cookie\Guard handle
…/­vendor/­stack/­builder/­src/­Stack/­StackedHttpKernel.php23
1. Stack\StackedHttpKernel handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php641
0. Illuminate\Foundation\Application run
…/­public/­index.php49

**Comment by ht2** [comment] 2016-05-16 08:18
Simply said, the query running on login is simply taking longer than the 30 seconds Mongo is configured to allow. However, I'm not 100% which query would even by taking that long - especially on login.

Could you provide some rough details as to the state of the database/application? E.g. how many LRS's you have setup with how many statements in total and on average in each? The query is failing at BaseDashboard.php#59, which is simply a query to grab the most recent statement....

https://github.com/LearningLocker/learninglocker/blob/develop/app/locker/data/dashboards/BaseDashboard.php#L59

Can I check - have you manually configured any indexes in the database?

**Comment by ngarafol** [comment] 2016-05-16 08:24
There is one LRS currently with 4168529 statements and counting. Database size is 8.804GB so roughly 2KB per statement. 

I did not configure any indexes manually.

**Comment by ht2** [comment] 2016-05-16 08:30
OK, this will definitely be an indexing issue - LL is not configured out of the box to run at enteprise scale (which you are definitely straying into). 

So to start I would make sure you check out my blog entry about indexing in LL here: https://learninglocker.net/blog/learning-locker-v1-12/

And then I would also suggest you think about contacting us here at HT2 directly about your solution and the kinds of challenges we know you are going to face moving at that kind of scale. 

For the moment, try adding those indexes manually and see if it helps, I believe it will. A word of warning, this will create huge amounts of extra data to your MongoDB size (roughly 25% of the total data size, which is different to the compressed Wired Tiger storage size..). Let me know if that makes a difference to your load times though.

**Comment by ht2** [comment] 2016-05-16 08:31
(and whilst I do implore you read through that blog, here is the tl;dr...)

```
db.statements.createIndex({stored: 1})
db.statements.createIndex({timestamp: 1})
db.statements.createIndex({active: 1})
db.statements.createIndex({voided:1})
db.statements.createIndex({lrs_id:1})
db.statements.createIndex({lrs_id:1, active:-1, voided:1})
db.statements.createIndex({lrs_id:1, 'statement.actor.mbox':1} )
db.statements.createIndex({'statement.actor.mbox':1})
db.statements.createIndex({lrs_id:1, 'statement.actor.account.name':1, 'statement.actor.account.homePage':1})
db.statements.createIndex({lrs_id:1, 'statement.actor.mbox':1} )
db.statements.createIndex({lrs_id:1, 'statement.verb.id':1})
db.statements.createIndex({lrs_id:1, 'statement.object.id':1})
db.statements.createIndex({lrs_id: 1, stored:-1})
db.statements.createIndex({lrs_id: 1, timestamp:-1})
db.statements.createIndex({'statement.id':1, lrs_id:1})
```

**Comment by ryansmith94** [comment] 2016-05-18 11:13
Closing this. I'll reopen if @ngarafol decides that didn't resolve the issue.

**Closed by ryansmith94** 2016-05-18 11:13 UTC
Labels: priority:low, status:unconfirmed, type:bug

**Comment by ngarafol** [comment] 2016-05-19 11:13
This fixed the issue with admin dashboard. Now new issue is with LRS view. There is still timeout of 30 seconds on url learning-locker-site/site#lrs. Looking at code, it tries to get count of records in statements collection that already has 20 indexes. Lrs collection has only one record due to using only one LRS. Do I need any more indexes for it to work properly?

**Comment by ht2** [comment] 2016-05-19 12:24
I pushed some updated code yesterday to `develop` that attempts to get the count to use a hint for the right index, so try pulling from develop (ensure you run a `composer install` as some of the new dependencies are important).

However, that shouldn't be affecting the counts on the site#lrs page. Can you ensure you have the `{lrs_id:1, active:-1, voided:1}` index in place on the statements collection?

**Comment by ngarafol** [comment] 2016-05-19 12:26
Yes, I have that index: 

 {
                "v" : 1,
                "key" : {
                        "lrs_id" : 1,
                        "active" : -1,
                        "voided" : 1
                },
                "name" : "lrs_id_1_active_-1_voided_1",
                "ns" : "LearningLocker.statements"
        },

Ok, will try new code from develop branch ;)

**Comment by ngarafol** [comment] 2016-05-19 13:36
Hmm develop branch behaves the same. Looking at mongo queries, there is cursorExhausted:1 in few queries. 

2016-05-19T15:23:17.089+0200 I COMMAND  [conn83] command admin.$cmd command: ping { ping: 1 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:37 locks:{} protocol:op_query 0ms
2016-05-19T15:23:17.089+0200 I COMMAND  [conn83] command admin.$cmd command: isMaster { isMaster: 1 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:178 locks:{} protocol:op_query 0ms
2016-05-19T15:23:17.090+0200 I COMMAND  [conn83] query LearningLocker.sessions query: { _id: "60e8289377b5b8f3346dbe88c0f90c83a1a6b355" } planSummary: IDHACK ntoskip:0 keysExamined:1 docsExamined:1 idhack:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:0 nreturned:1 reslen:391 locks:{ Global: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } 0ms
2016-05-19T15:23:17.390+0200 I COMMAND  [conn83] query LearningLocker.users query: { _id: ObjectId('572c3f00dd4239d3148b4567') } planSummary: IDHACK ntoreturn:1 ntoskip:0 keysExamined:1 docsExamined:1 idhack:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:0 nreturned:1 reslen:326 locks:{ Global: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } 273ms
2016-05-19T15:23:17.409+0200 I COMMAND  [conn83] query LearningLocker.lrs planSummary: COLLSCAN ntoreturn:0 ntoskip:0 keysExamined:0 docsExamined:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:1 nreturned:1 reslen:397 locks:{ Global: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 2 } }, Collection: { acquireCount: { r: 2 } } } 17ms
2016-05-19T15:23:47.467+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:55991 #87 (13 connections now open)
2016-05-19T15:23:47.467+0200 I COMMAND  [conn87] command admin.$cmd command: isMaster { isMaster: 1 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:178 locks:{} protocol:op_query 0ms
2016-05-19T15:23:47.467+0200 I COMMAND  [conn87] command admin.$cmd command: buildInfo { buildInfo: 1 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:1122 locks:{} protocol:op_query 0ms
2016-05-19T15:23:47.469+0200 I COMMAND  [conn87] command LearningLocker.$cmd command: saslStart { saslStart: 1, mechanism: "SCRAM-SHA-1", payload: "xxx", autoAuthorize: 1 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:226 locks:{} protocol:op_query 1ms
2016-05-19T15:23:47.484+0200 I COMMAND  [conn87] command LearningLocker.$cmd command: saslContinue { saslContinue: 1, conversationId: 1, payload: "Yz1iaXdzLHI9ZmU5YTljNzZhZGM2MWRiYjA3NzNlMmMyMWM0Mjg5Y2FkNWMzZjE4MTg4NC9DZ0VDdTd1dHl5LzRGUVdGU0tMUUV0MGVQSDZxLHA9a1VESHRZQmY0Ti9BQVhTQkZxRGowKzZaQkVZPQ==" } keyUpdates:0 writeConflicts:0 numYields:0 reslen:118 locks:{} protocol:op_query 0ms
2016-05-19T15:23:47.485+0200 I ACCESS   [conn87] Successfully authenticated as principal debian on LearningLocker
2016-05-19T15:23:47.485+0200 I COMMAND  [conn87] command LearningLocker.$cmd command: saslContinue { saslContinue: 1, conversationId: 1, payload: "" } keyUpdates:0 writeConflicts:0 numYields:0 reslen:78 locks:{} protocol:op_query 0ms
2016-05-19T15:23:47.485+0200 I COMMAND  [conn87] command admin.$cmd command: ping { ping: 1 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:37 locks:{} protocol:op_query 0ms
2016-05-19T15:23:47.486+0200 I WRITE    [conn87] update LearningLocker.sessions query: { _id: "60e8289377b5b8f3346dbe88c0f90c83a1a6b355" } update: { $set: { payload: BinData(2, 613A343A7B733A363A225F746F6B656E223B733A34303A2279714A655A4C38564F59497876543363756E79414C5633554362454C4E4E6C7965714130566C576C223B733A353A...), last_activity: new Date(1463664227466) } } keysExamined:1 docsExamined:1 nMatched:1 nModified:1 keyUpdates:0 writeConflicts:0 numYields:0 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { w: 1 } }, Collection: { acquireCount: { w: 1 } } } 0ms
2016-05-19T15:23:47.486+0200 I COMMAND  [conn87] command LearningLocker.$cmd command: update { update: "sessions", updates: [ { q: { _id: "60e8289377b5b8f3346dbe88c0f90c83a1a6b355" }, u: { $set: { payload: BinData(2, 613A343A7B733A363A225F746F6B656E223B733A34303A2279714A655A4C38564F59497876543363756E79414C5633554362454C4E4E6C7965714130566C576C223B733A353A...), last_activity: new Date(1463664227466) } }, multi: false, upsert: true } ], writeConcern: { w: 1 } } keyUpdates:0 writeConflicts:0 numYields:0 reslen:55 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { w: 1 } }, Collection: { acquireCount: { w: 1 } } } protocol:op_query 0ms

**Comment by ht2** [comment] 2016-05-19 13:44
Very odd

```
2016-05-19T15:23:17.409+0200 I COMMAND [conn83] query LearningLocker.lrs planSummary: COLLSCAN ntoreturn:0 ntoskip:0 keysExamined:0 docsExamined:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:1 nreturned:1 reslen:397 locks:{ Global: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 2 } }, Collection: { acquireCount: { r: 2 } } } 17ms
``` 

The `lrs` collection is small - I don't see why there would be any issue with it. Looks like a mongo issue to me.

I would try reproducing some of these queries at the mongo CLI level and see if you can replicate at all.

For example, the actual count query that the site#lrs page is doing for each LRS will look something like...

`statements.count({"lrs_id":{"$id":"yourLRS_id"}})`

**Comment by ngarafol** [comment] 2016-05-20 08:24
Query works on mongo cli. Also, mongodb 3.2 with tiger (default in 3.2) is used.
Any suggestion?

**Comment by ngarafol** [comment] 2016-05-20 08:39
This is only thing that shows in developer tools: Status: 500 Error: localhost:27017: Read timed out after reading 0 bytes, waited for 30.000000 seconds{"error":{"type":"MongoCursorTimeoutException","message":"localhost:27017: Read timed out after reading 0 bytes, waited for 30.000000 seconds","file":"\/var\/www\/learninglocker\/vendor\/jenssegers\/mongodb\/src\/Jenssegers\/Mongodb\/Collection.php","line":59}}

**Comment by ht2** [comment] 2016-05-20 08:46
If those all run fine, then my guess is a different query is the problem. Setup a slow log in mongo and that should point out the exact query that is failing at >30s

**Comment by ngarafol** [comment] 2016-05-20 10:14
How come with indexes on statements collection count operation still takes much time? Is there something I am doing wrong? 

Here are logged queries over 29sec:

2016-05-20T11:04:30.129+0200 I COMMAND  [conn30] command LearningLocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: IXSCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:55218 reslen:62 locks:{ Global: { acquireCount: { r: 110438 } }, Database: { acquireCount: { r: 55219 }, acquireWaitCount: { r: 7 }, timeAcquiringMicros: { r: 23226 } }, Collection: { acquireCount: { r: 55219 } } } protocol:op_query 1647678ms
2016-05-20T11:04:30.129+0200 I COMMAND  [conn33] command LearningLocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: IXSCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:52870 reslen:62 locks:{ Global: { acquireCount: { r: 105742 } }, Database: { acquireCount: { r: 52871 }, acquireWaitCount: { r: 5 }, timeAcquiringMicros: { r: 36362 } }, Collection: { acquireCount: { r: 52871 } } } protocol:op_query 1326165ms
2016-05-20T11:04:30.129+0200 I COMMAND  [conn28] command LearningLocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: IXSCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:51836 reslen:62 locks:{ Global: { acquireCount: { r: 103674 } }, Database: { acquireCount: { r: 51837 }, acquireWaitCount: { r: 7 }, timeAcquiringMicros: { r: 21751 } }, Collection: { acquireCount: { r: 51837 } } } protocol:op_query 1214891ms
2016-05-20T11:04:30.147+0200 I COMMAND  [conn34] command LearningLocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: IXSCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:52070 reslen:62 locks:{ Global: { acquireCount: { r: 104142 } }, Database: { acquireCount: { r: 52071 }, acquireWaitCount: { r: 6 }, timeAcquiringMicros: { r: 11683 } }, Collection: { acquireCount: { r: 52071 } } } protocol:op_query 1248662ms
2016-05-20T11:04:30.437+0200 I NETWORK  [conn30] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [127.0.0.1:56193]
2016-05-20T11:04:30.437+0200 I NETWORK  [conn28] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [127.0.0.1:56188]
2016-05-20T11:04:30.437+0200 I NETWORK  [conn34] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [127.0.0.1:56203]
2016-05-20T11:04:30.438+0200 I NETWORK  [conn33] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [127.0.0.1:56201]
2016-05-20T11:19:46.200+0200 I COMMAND  [conn18] command LearningLocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: IXSCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:53584 reslen:62 locks:{ Global: { acquireCount: { r: 107170 } }, Database: { acquireCount: { r: 53585 }, acquireWaitCount: { r: 2 }, timeAcquiringMicros: { r: 14611 } }, Collection: { acquireCount: { r: 53585 } } } protocol:op_query 1307250ms
2016-05-20T11:19:46.200+0200 I COMMAND  [conn39] command LearningLocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: IXSCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:52845 reslen:62 locks:{ Global: { acquireCount: { r: 105692 } }, Database: { acquireCount: { r: 52846 } }, Collection: { acquireCount: { r: 52846 } } } protocol:op_query 1198135ms
2016-05-20T11:19:46.209+0200 I NETWORK  [conn18] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [127.0.0.1:56055]
2016-05-20T11:19:46.209+0200 I NETWORK  [conn39] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [127.0.0.1:56214]

**Comment by ht2** [comment] 2016-05-20 10:49
Sorry @ngarafol, I've got no idea why that would be taking so long. Think you will need to reach out to a Mongo expert to analyse the issue. We see our Mongo instances handle counts in the millions in milliseconds, so there may be something else at play here.

**Comment by ngarafol** [comment] 2016-05-23 11:25
Can you just do this query on some statements collection with more than a million documents and post back results? Ofcourse, change objectid :)  

> db.statements.find({ lrs_id: ObjectId('572c4ecbdd4239f3148b4567') }).explain("executionStats")

I got over 900 seconds on 5 million documents collection since 99% of that time took for mongo to fetch collection. And it does not make sense to fetch whole collection, so I just want to make sure how long does it take in your case.

Here is pastebin of my case: http://pastebin.com/tUyXsgx5

**Comment by ht2** [comment] 2016-05-23 11:42
Here you go, note I've included the counts at the top - this is running on a modest sized LRS.

http://pastebin.com/DnCenn1r

On a count, the collection is not being fetched in its entirety, it is counting the index where available.

E.g.
```
mongos> db.statements.explain().count({ lrs_id: ObjectId('REDACTED')})
{
        "queryPlanner" : {
                "mongosPlannerVersion" : 1,
                "winningPlan" : {
                        "stage" : "SINGLE_SHARD",
                        "shards" : [
                                {
                                        "shardName" : "REDACTED",
                                        "connectionString" : "REDACTED",
                                        "serverInfo" : {
                                                "host" : "REDACTED",
                                                "port" : REDACTED,
                                                "version" : "3.0.9",
                                                "gitVersion" : "20d60d3491908f1ae252fe452300de3978a040c7"
                                        },
                                        "plannerVersion" : 1,
                                        "namespace" : "REDACTED.statements",
                                        "indexFilterSet" : false,
                                        "parsedQuery" : {
                                                "lrs_id" : {
                                                        "$eq" : ObjectId("REDACTED")
                                                }
                                        },
                                        "winningPlan" : {
                                                "stage" : "COUNT",
                                                "inputStage" : {
                                                        "stage" : "COUNT_SCAN",
                                                        "keyPattern" : {
                                                                "lrs_id" : NumberLong(1)
                                                        },
                                                        "indexName" : "lrs_id_1",
                                                        "isMultiKey" : false
                                                }
                                        },
                                        "rejectedPlans" : [ ]
                                }
                        ]
                }
        },
        "ok" : 1
}
```

Also note, a find will return a cursor with up to 20 iterations by default (so you should see at most 20 records coming back as a result): https://docs.mongodb.com/v3.0/reference/method/db.collection.find/#iterate-the-returned-cursor, but it shouldn't be actively fetching the entire matching record set into memory. The initial batch size will be in the region of 1MB (https://docs.mongodb.com/manual/core/cursors/#cursor-batches)

**Comment by ngarafol** [comment] 2016-05-23 11:54
Could be that I use 3.2.6 version, and you use 3.0.9 ? :)

**Comment by ht2** [comment] 2016-05-23 12:05
I highly doubt it. We are using the WiredTiger storage engine, which is the default in 3.2 and the one you will be using.

Are you using a sharded setup? Do you have replica sets? Is the Mongo instance hosted on its own server or are you sharing resources with the application server?

**Comment by ngarafol** [comment] 2016-05-23 12:18
I have single VM 2core, 8gb ram shared with app server and mongodb. I might try local sharding to see if anything improves, since mongo is using only one core.

**Comment by ht2** [comment] 2016-05-23 12:55
This may be of interest: https://learninglocker.net/blog/lrs-enterprise-hosting/

**Comment by ngarafol** [comment] 2016-06-06 08:17
There is something definitely wrong. Look at this two queries logged:
first:
learninglocker-db | 2016-06-06T07:44:11.942+0000 I COMMAND  [conn1] command learninglocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: COUNT_SCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:40501 reslen:62 locks:{ Global: { acquireCount: { r: 81004 } }, Database: { acquireCount: { r: 40502 } }, Collection: { acquireCount: { r: 40502 } } } protocol:op_query 1238ms

second: 
learninglocker-db | 2016-06-06T08:08:49.045+0000 I COMMAND  [conn21] command learninglocker.statements command: count { count: "statements", query: { lrs_id: ObjectId('572c4ecbdd4239f3148b4567') } } planSummary: IXSCAN { lrs_id: 1 } keyUpdates:0 writeConflicts:0 numYields:41075 reslen:62 locks:{ Global: { acquireCount: { r: 82152 }, acquireWaitCount: { r: 13 }, timeAcquiringMicros: { r: 1191 } }, Database: { acquireCount: { r: 41076 } }, Collection: { acquireCount: { r: 41076 } } } protocol:op_query 230029ms

Query looks the same to me. First time it uses count_scan and finishes in under 2 seconds, second time it uses indexscan and finishes in over 230 seconds. That can not be right.

**Comment by ryansmith94** [comment] 2016-06-07 09:22
That is certainly strange @ngarafol, I think you'd have to discuss this issue with Mongo experts.
