### ISSUE TITLE
Status: 500 Error: mcrypt_encrypt(): Key of size 14 not supported by this algorithm.

### ISSUE THREAD

**Issue by blumonkey** [LearningLocker/learninglocker#677] opened 2015-06-27 07:59 UTC
I have just updated my LearningLocker and was received by this message on `/public/index.html`. Any clues?

    Status: 500 Error: mcrypt_encrypt(): Key of size 14 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported

**Comment by blumonkey** [comment] 2015-06-29 08:36
For anyone who is facing the same problem, I followed https://octobercms.com/forum/post/mcrypt-encrypt-key-of-size-11-not-supported-by-this-algorithm-only-keys-of-sizes-16-24-or-32-supported to change the encryption key to size-16. I don't know whether this is right or not but it worked.

**Comment by ryansmith94** [comment] 2015-06-29 09:10
Duplicate of #488

**Closed by ryansmith94** 2015-06-29 09:10 UTC
