### ISSUE TITLE
State API returns 400 Bad Request when PUTing a JSON object

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/learninglocker#493] opened 2015-01-23 12:08 UTC
**Version**
http://lrs.learninglocker.net/lrs/

**Steps to reproduce the bug**
Using TinCanJS, PUT a document of type application/json twice in a row without using etags. Use the following document contents:

``` {"location":1,"attemptDuration":9083,"attemptComplete":false} ```

**Expected behaviour**
The document should be updated returning 204 No Content. 

**Actual behaviour**
400 Bad Request. ``` {"error":true,"success":false,"message":"sha1() expects parameter 1 to be string, array given","trace":"#0 [internal function]: Illuminate\\Exception\\Handler->handleError(2, 'sha1() expects ...', '\/var\/www\/html\/l...', 66, Array)\n#1 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/models\/DocumentAPI.php(66): sha1(Array)\n#2 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/models\/DocumentAPI.php(27): DocumentAPI->setSha(Array)\n#3 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/models\/DocumentAPI.php(126): DocumentAPI->putContent('{\"location\":1,\"...', 'application\/jso...')\n#4 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/locker\/repository\/Document\/EloquentDocumentRepository.php(254): DocumentAPI->setContent(Array, 'PUT')\n#5 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/locker\/repository\/Document\/EloquentDocumentRepository.php(95): Locker\\Repository\\Document\\EloquentDocumentRepository->storeStateDoc('54c13edd66562fe...', Array, '2015-01-23T11:5...', 'PUT')\n#6 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/controllers\/xapi\/DocumentController.php(94): Locker\\Repository\\Document\\EloquentDocumentRepository->store('54c13edd66562fe...', 'state', Array, '2015-01-23T11:5...', 'PUT')\n#7 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/controllers\/xapi\/DocumentController.php(113): Controllers\\xAPI\\DocumentController->store()\n#8 \/var\/www\/html\/learninglocker\/subdomains\/live\/app\/controllers\/xapi\/BaseController.php(37): Controllers\\xAPI\\DocumentController->update()\n#9 [internal function]: Controllers\\xAPI\\BaseController->selectMethod()\n#10 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(231): call_user_func_array(Array, Array)\n#11 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(93): Illuminate\\Routing\\Controller->callAction('selectMethod', Array)\n#12 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(62): Illuminate\\Routing\\ControllerDispatcher->call(Object(Controllers\\xAPI\\StateController), Object(Illuminate\\Routing\\Route), 'selectMethod')\n#13 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(962): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'Controllers\\\\xAP...', 'selectMethod')\n#14 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()\n#15 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(109): call_user_func_array(Object(Closure), Array)\n#16 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1028): Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))\n#17 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(996): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#18 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(776): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#19 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(746): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#20 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/asm89\/stack-cors\/src\/Asm89\/Stack\/Cors.php(51): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Asm89\\Stack\\Cors->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#23 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#24 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#25 \/var\/www\/html\/learninglocker\/subdomains\/live\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(642): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#26 \/var\/www\/html\/learninglocker\/subdomains\/live\/public\/index.php(49): Illuminate\\Foundation\\Application->run()\n#27 {main}"} ```

**Server information**
http://lrs.learninglocker.net/lrs/

**Client information**
OS: OS X
Browser: Chrome

**Additional information**
* Possibly related to https://github.com/LearningLocker/learninglocker/issues/491
* Bug does not occur with content type application/octet-stream and content ```1```

**Comment by ryansmith94** [comment] 2015-02-12 12:03
Hi @garemoko, this should be fixed in the [issue/493](https://github.com/LearningLocker/learninglocker/tree/issue/493) branch. If you can pull and test that branch that would be helpful. Once you confirm that the issue is fixed for you I'll make a pull request out of that branch.

**Comment by ryansmith94** [comment] 2015-02-24 14:51
This should now be resolved on the develop branch.

**Comment by ryansmith94** [comment] 2015-02-25 14:59
Had to make a few changes to pass the conformance tests that may effect this issue. If someone can test this issue with the issue/conformance branch that would be awesome.

**Comment by garemoko** [comment] 2015-02-25 18:12
*looks at @davidpesce*

**Comment by davidpesce** [comment] 2015-02-25 21:16
Will do! I'm tied up this afternoon, but will be able to take a look tonight and tomorrow.

**Comment by davidpesce** [comment] 2015-02-26 02:48
@ryansmith94 Confirmed! This issue is resolved.

**Comment by ryansmith94** [comment] 2015-02-26 09:51
Brilliant thank you @davidpesce! :smile:

**Closed by ryansmith94** 2015-02-26 09:51 UTC
Labels: priority:medium, status:unmerged, type:bug
