### ISSUE TITLE
Create LRS client with xapi

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#917] opened 2017-04-05 17:56 UTC
I am creating a LMS platform to be connected with a LRS (in this case learning locker LRS). I am trying to create new clients with xapi through php. I have no ideia how to do it. Any help?

**Comment by ryansmith94** [comment] 2017-04-06 10:06
Duplicate of #914...

**Closed by ryansmith94** 2017-04-06 10:06 UTC
Labels: priority:low, status:unconfirmed, type:question
