### ISSUE TITLE
New install - 500 Error: Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by james-siteclick** [LearningLocker/learninglocker#574] opened 2015-04-02 13:24 UTC
1.3.8

**Steps to reproduce the bug**
- Clone git repository 
- Do Composer update
- Do artisan migrate
- Go to /register
- Register first super user

**Expected behaviour**
Go to dashboard and create first LRS

**Actual behaviour**
- App redirects to / with error message:

Status: 500 Error: Invalid argument supplied for foreach()
Whoops, looks like something went wrong.

Stack trace:
#0 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(424): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/Applications/M...', 424, Array)
#1 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#2 /Applications/MAMP/htdocs/learninglocker/app/locker/data/dashboards/AdminDashboard.php(63): Illuminate\Database\Eloquent\Builder->get()
#3 /Applications/MAMP/htdocs/learninglocker/app/locker/data/dashboards/AdminDashboard.php(24): app\locker\data\dashboards\AdminDashboard->actorCount()
#4 /Applications/MAMP/htdocs/learninglocker/app/routes.php(26): app\locker\data\dashboards\AdminDashboard->getFullStats()
#5 [internal function]: {closure}()
#6 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#7 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 /Applications/MAMP/htdocs/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 /Applications/MAMP/htdocs/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run()
#17 {main} [] []

User has been created in Mongo:

{
    '_id': ObjectId("551d3fb98f437e27a10041a7"),
    'name': 'James xxx',
    'email': 'xxx',
    'verified': 'no',
    'role': 'super',
    'password': 'xxx',
    'updated_at': ISODate("2015-04-02T13:10:17.585Z"),
    'created_at': ISODate("2015-04-02T13:10:17.585Z")
}

**Server information**
OSX
MAMP
mongodb

**Client information**
OS: OSX
Browser: Chrome (latest)

**Additional information**

**Comment by ryansmith94** [comment] 2015-04-02 14:15
Hi @james-siteclick, thanks for reporting this issue and following our guidelines. I need to try to reproduce your issue, I'm a bit busy today, so I'll probably check it out Monday, sorry for the delay.

In the meantime, please [verify your user](http://docs.learninglocker.net/installation/#register-your-first-user) and try to create an LRS again.

**Comment by ryansmith94** [comment] 2015-04-07 10:18
Hi @james-siteclick, can you please clear your "app/storage/logs/laravel.log" file, then reproduce the issue and paste the contents of your "app/storage/logs/laravel.log" file here.

**Comment by james-siteclick** [comment] 2015-04-09 08:48
Hi @ryansmith94  thanks for your help.  I cleared everything and tried again, here's the log output:

[2015-04-09 08:46:39] local.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:424
Stack trace:
#0 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(424): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/Applications/M...', 424, Array)
#1 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#2 /Applications/MAMP/htdocs/learninglocker/app/locker/data/dashboards/AdminDashboard.php(63): Illuminate\Database\Eloquent\Builder->get()
#3 /Applications/MAMP/htdocs/learninglocker/app/locker/data/dashboards/AdminDashboard.php(24): app\locker\data\dashboards\AdminDashboard->actorCount()
#4 /Applications/MAMP/htdocs/learninglocker/app/routes.php(26): app\locker\data\dashboards\AdminDashboard->getFullStats()
#5 [internal function]: {closure}()
#6 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#7 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 /Applications/MAMP/htdocs/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 /Applications/MAMP/htdocs/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run()
#17 {main} [] []
[2015-04-09 08:46:39] local.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:424
Stack trace:
#0 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(424): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/Applications/M...', 424, Array)
#1 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#2 /Applications/MAMP/htdocs/learninglocker/app/locker/data/dashboards/AdminDashboard.php(63): Illuminate\Database\Eloquent\Builder->get()
#3 /Applications/MAMP/htdocs/learninglocker/app/locker/data/dashboards/AdminDashboard.php(24): app\locker\data\dashboards\AdminDashboard->actorCount()
#4 /Applications/MAMP/htdocs/learninglocker/app/routes.php(26): app\locker\data\dashboards\AdminDashboard->getFullStats()
#5 [internal function]: {closure}()
#6 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#7 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 /Applications/MAMP/htdocs/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 /Applications/MAMP/htdocs/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 /Applications/MAMP/htdocs/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run()
#17 {main} [] []

**Comment by ryansmith94** [comment] 2015-04-10 10:58
Thanks for that, I think I've found a fix :+1:

**Comment by ryansmith94** [comment] 2015-04-10 11:00
Hi @james-siteclick, this should be fixed in the [issue/574 branch](https://github.com/LearningLocker/learninglocker/tree/issue/574). If you can pull and test that branch that would be helpful. Once you confirm that the issue is fixed for you we'll merge the fix.

**Comment by Lupei** [comment] 2015-04-10 13:53
Hello @ryansmith94, I have the same problem than @james-siteclick. I tried you fix but I still have the problem with this log :

[2015-04-10 13:43:06] local.INFO: Pretending to mail message to: foo@bar.com [] []
[2015-04-10 13:43:06] local.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:424
Stack trace:
#0 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(424): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/var/www/html/l...', 424, Array)
#1 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#2 /var/www/html/learninglocker/learninglocker/app/locker/data/dashboards/AdminDashboard.php(63): Illuminate\Database\Eloquent\Builder->get()
#3 /var/www/html/learninglocker/learninglocker/app/locker/data/dashboards/AdminDashboard.php(24): app\locker\data\dashboards\AdminDashboard->actorCount()
#4 /var/www/html/learninglocker/learninglocker/app/routes.php(26): app\locker\data\dashboards\AdminDashboard->getFullStats()
#5 [internal function]: {closure}()
#6 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#7 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/learninglocker/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 /var/www/html/learninglocker/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run()
#17 {main} [] []
[2015-04-10 13:43:06] local.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:424
Stack trace:
#0 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(424): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/var/www/html/l...', 424, Array)
#1 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#2 /var/www/html/learninglocker/learninglocker/app/locker/data/dashboards/AdminDashboard.php(63): Illuminate\Database\Eloquent\Builder->get()
#3 /var/www/html/learninglocker/learninglocker/app/locker/data/dashboards/AdminDashboard.php(24): app\locker\data\dashboards\AdminDashboard->actorCount()
#4 /var/www/html/learninglocker/learninglocker/app/routes.php(26): app\locker\data\dashboards\AdminDashboard->getFullStats()
#5 [internal function]: {closure}()
#6 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#7 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/learninglocker/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/learninglocker/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 /var/www/html/learninglocker/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run()
#17 {main} [] []

(I'm on Xunbuntu 14.04.02)

**Comment by ryansmith94** [comment] 2015-04-10 14:31
Hi @Lupei. Can you please copy and paste lines 62 to 64 from "app/locker/data/dashboards/AdminDashboard.php"?

**Comment by Lupei** [comment] 2015-04-10 15:25
Hi @ryansmith94, there it is : 

  public function actorCount(){
    return count( \Statement::distinct('statement.actor.mbox')->remember(5)->get() );
  }

**Comment by SamGreen9** [comment] 2015-04-10 15:55
Hi  @ryansmith94, you pointed me here from the Google Forum, I'm facing the same issue, running from a Ubuntu cloud server on AWS. The issue is persisting after following your advice from there. Please let me know if there's anything I can do or if there are any log files you'd like to see that might be useful. Cheers!

**Comment by ryansmith94** [comment] 2015-04-13 11:36
@Lupei that isn't using [the fix I mentioned] (https://github.com/LearningLocker/learninglocker/issues/574#issuecomment-91516877). I know this because [the line that you pasted has been changed by my fix](https://github.com/LearningLocker/learninglocker/commit/e7c8d0a0c6adcad443d07aa2ab0d1855d024c684).

@SamGreen9 thanks Sam, I believe this issue is fixed, however the fix is not yet released. This fix will go out this Friday with out weekly release (v1.3.10). Sorry for any inconvenience. In the meantime I can assist you if the password change is urgent.

**Comment by Lupei** [comment] 2015-04-13 11:47
@ryansmith94 You're right, thanks. It works now !

**Comment by ryansmith94** [comment] 2015-04-13 12:18
Brilliant! No worries. Thank you for testing it @Lupei :smile:

**Comment by SamGreen9** [comment] 2015-04-13 13:13
@ryansmith94 My apologies, after checking my line 63 I realised that I'd reinstalled using 'composer create-project', but this didn't include the latest fix. Installing your fix now, thanks!

**Comment by ryansmith94** [comment] 2015-04-13 13:14
@SamGreen9 awesome no worries! :+1:

**Closed** 2015-04-13 14:49 UTC
Labels: priority:high, status:unmerged, type:bug
