### ISSUE TITLE
XAPI Cannot query statements using account object as the actor parameter

### ISSUE THREAD

**Issue by james-siteclick** [LearningLocker/learninglocker#519] opened 2015-02-17 13:03 UTC
Version 1.3

**Steps to reproduce**
Do an HTTP get to the XAPI for statements, if I query with 'agent' only containing an mbox it works OK, but if do a query parameter 'agent' set to an opaque account as the following:
{
objectType : "Agent",
account : {
  name : "1234"
  homePage : "http://example.com"
}
}

**Expected behaviour**
Retrieve a list of statements relating to the user account object supplied.

**Actual behaviour**
PHP error in Learning Locker:
strtolower() expects parameter 1 to be string, array given

**Server information**
mongo DB with HTTP basic auth.

**Client information**
OSX Yosemite
Browser: Chrome

**Comment by ryansmith94** [comment] 2015-02-17 14:47
Hi @james-siteclick, thanks for reporting this issue and following our guidelines, this has been reproduced and should be fixed soon. Apologies for any inconvenience this has caused you.

The issue is in the Eloquent Statement Repository.

**Comment by ryansmith94** [comment] 2015-02-17 16:31
If this is urgent and specific to Learning Locker, please consider using our [aggregation API](http://docs.learninglocker.net/statements_api/#aggregate) in the meantime.

**Comment by ryansmith94** [comment] 2015-02-17 16:42
Hi @james-siteclick, this should be fixed in the [issue/519](https://github.com/LearningLocker/learninglocker/tree/issue/519) branch. If you can pull and test that branch that would be helpful. Once you confirm that the issue is fixed for you I'll make a pull request out of that branch.

**Comment by james-siteclick** [comment] 2015-02-17 17:39
Many thanks, I think that's fixed now but haven't tested extensively

**Comment by ryansmith94** [comment] 2015-02-17 21:29
You're welcome. Ok thanks for letting me know.

**Comment by ryansmith94** [comment] 2015-02-17 21:31
The fix has been merged to the develop branch and will be released with 1.3.4.

**Closed** 2015-02-17 21:31 UTC
Labels: priority:high, status:unmerged, type:bug
