### ISSUE TITLE
multiple errors on reporting/statements

### ISSUE THREAD

**Issue by pkconcept** [LearningLocker/learninglocker#510] opened 2015-02-11 21:32 UTC
**Version**
1.3.2

**Steps to reproduce the bug**
1. Go to `lrs/[id]/reporting/[key]/statements`.

**Expected behaviour**
I expect `$` (jQuery) to be defined when the code below is ran. I expect this because jQuery should be loaded before it can be used in the code below.

```
<script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>
```

**Actual behaviour**
jQuery is not defined (see error below).

`Uncaught ReferenceError: $ is not defined`

**Server information**
Debian wheezy, Apache 2, PHP 5.4.36-0+deb7u3

**Client information**
OS: Windows 7
Browser: All (Firefox, Chrome, Opera, Safari)

**Additional information**
1. All other jquery functions are disabled after.
2. Links inside the page like  `<a href=":atc">` are not working.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
          <title>
        Learning Locker: an open source learning record store (LRS)
      </title>
          <script src="http://devserver/js-localization/localization.js"></script>
      [ --- cutted --]
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      });
    </script>
  </body>
</html>
```

**Comment by ryansmith94** [comment] 2015-02-11 21:50
Hi @pkconcept, thanks for reporting this issue. Please edit your comment to follow our [guidelines](docs.learninglocker.net/issues/).

**Comment by pondermatic** [comment] 2015-02-11 21:55
Here is the correct link to the [guidelines](https://github.com/LearningLocker/learninglocker/blob/develop/contributing.md).

**Comment by ryansmith94** [comment] 2015-02-11 22:02
That is the correct link, but whilst those guidelines are good before making an issue, if you need to edit an issue, the link I gave is where you probably end up hence why I linked there instead.

Maybe this is a flaw in those guidelines and we should move the guidelines from the website inside that document.

Really appreciate you trying to get involved @pondermatic :smile:

**Comment by pondermatic** [comment] 2015-02-11 22:15
When I click on the link to the guidelines that you provided, I received a github 404 page.

**Comment by ryansmith94** [comment] 2015-02-11 22:21
Haha fixed that now, my bad. Fixed now.

**Comment by pkconcept** [comment] 2015-02-11 22:28
Sorry for all it's my first issue... ;)

**Comment by ryansmith94** [comment] 2015-02-11 22:35
No worries thanks for updating it.

**Comment by ryansmith94** [comment] 2015-02-11 22:41
@pkconcept I've just updated your comment a bit, hopefully my update helps you when making issues here in future :+1:

**Comment by pkconcept** [comment] 2015-02-11 23:04
yes, nice comment ! thank's a lot :)

**Comment by pkconcept** [comment] 2015-02-11 23:16
Found where is error : learninglocker/app/views/partials/reporting/statements.blade.php
last @section  ( footer ) without @stop

**Comment by pkconcept** [comment] 2015-02-11 23:18
but.. don't know why all links like this one doesn't work...

`<a href="act:4:Code_de_la_route">Code de la route </a>`

**Comment by ryansmith94** [comment] 2015-02-12 10:19
This should be fixed in the [issue/510](https://github.com/LearningLocker/learninglocker/tree/issue/510) branch. If you can pull and test that branch that would be helpful. Once you confirm that the issue is fixed for you I'll make a pull request out of that branch.

**Comment by pkconcept** [comment] 2015-02-12 10:30
Tested and fixed, thanks :)

**Comment by ryansmith94** [comment] 2015-02-12 10:42
Great stuff, thanks for the quick response :)

**Closed** 2015-02-12 10:49 UTC
Labels: priority:low, status:confirmed, type:bug
