### ISSUE TITLE
Installation doesn't complete

### ISSUE THREAD

**Issue by cwarwicker** [LearningLocker/learninglocker#636] opened 2015-05-21 09:37 UTC
**Version**
develop at 8a36798f6505e99506eaf2fbef4942b4f81aa973

**Steps to reproduce the bug**
Followed install instructions

**Expected behaviour**
System should install properly and be able to be used in web browser

**Actual behaviour**
The composer install doesn't finish successfully and then there is a fatal error when accessed through the web browser.

**Server information**
Ampps
mongodb

**Client information**
OS: windows7
Browser: chrome

**Additional information**
The composer install ends with this error:

  - Installing classpreloader/classpreloader (1.0.2)
    Downloading: Connecting...    Failed to download classpreloader/classpreload
er from dist: The "https://api.github.com/repos/mtdowling/ClassPreloader/zipball
/2c9f3bcbab329570c57339895bd11b5dd3b00877" file could not be downloaded (HTTP/1.
1 404 Not Found)
    Now trying to download from source
  - Installing classpreloader/classpreloader (1.0.2)
    Cloning 2c9f3bcbab329570c57339895bd11b5dd3b00877
  [RuntimeException]
  Failed to clone git@github.com:mtdowling/ClassPreloader.git, git was not fo
  und, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [pac
kages1] ... [packagesN]

Then when accessing /public in the web browser, the fatal error is:

Fatal error: require(): Failed opening required 'C:\Ampps\www\learninglocker\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Ampps\www\learninglocker\bootstrap\autoload.php on line 17

I have looked and there is no autoload.php file in the /vendor/ directory, presumably because that was what didn't get downloaded in the composer install.

**Comment by ryansmith94** [comment] 2015-05-21 10:54
Hi @cwarwicker, thanks for reporting this issue and using our template. I have heard of this issue in our [chat room](https://gitter.im/LearningLocker/learninglocker). I think this will be resolved by #637 but ultimately this is an issue with Composer.

**Comment by cwarwicker** [comment] 2015-05-21 12:41
Ok. Is there a workaround I can use for the time being? Is it just that one autoloader file being missing causing the problem? If so, can I just get that 1 file from somewhere?

Cheers

**Comment by ryansmith94** [comment] 2015-05-21 12:45
I'm not too sure because I've not been able to reproduce the issue. I'd take this issue up with Composer.

**Comment by cwarwicker** [comment] 2015-05-21 14:21
Ok. I've found they have an issue open about it:

https://github.com/composer/composer/issues/4030

**Comment by ryansmith94** [comment] 2015-05-21 15:15
Nice, thank you for the update :+1:

**Comment by ryansmith94** [comment] 2015-05-22 09:21
@cwarwicker thanks for linking to that issue. I didn't realise that our Composer lock file had become outdated. This should be fixed in #639. It'll be merged into the develop branch and released with v1.4.2 today.

**Closed** 2015-05-22 09:26 UTC
Labels: priority:high, status:unconfirmed, type:bug
