### ISSUE TITLE
MongoCursorTimeoutException

### ISSUE THREAD

**Issue by Hovard** [LearningLocker/learninglocker#764] opened 2015-12-10 11:41 UTC
We get the exception below when navigating the statements in the hosted solution of lrs.learninglocker.net and when we do API statement queries. It can be reproduced for instance by browsing in the statements using the paging functions or running a query "getall" statements on a database with just 24 statements, all from 1 agent/user. It sometimes work when querying 1000 statements, but fails randomly here also.

None of our local custom reports using the API work, so this is high priority for us.

Exception:
MongoCursorTimeoutException thrown with message "582505-db1.ht2.co.uk:27017: Read timed out after reading 0 bytes, waited for 30.000000 seconds"

Stacktrace:
#25 MongoCursorTimeoutException in /var/www/html/learninglocker/subdomains/live/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php:196
#24 MongoCursor:rewind in <#unknown>:0
#23 iterator_to_array in /var/www/html/learninglocker/subdomains/live/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php:196
#22 Jenssegers\Mongodb\Query\Builder:getFresh in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1336
#21 Illuminate\Database\Query\Builder:get in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:415
#20 Illuminate\Database\Eloquent\Builder:getModels in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:151
#19 Illuminate\Database\Eloquent\Builder:get in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:285
#18 Illuminate\Database\Eloquent\Builder:ungroupedPaginate in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:247
#17 Illuminate\Database\Eloquent\Builder:paginate in /var/www/html/learninglocker/subdomains/live/app/controllers/ReportingController.php:92
#16 ReportingController:statements in <#unknown>:0
#15 call_user_func_array in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:231
#14 Illuminate\Routing\Controller:callAction in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:93
#13 Illuminate\Routing\ControllerDispatcher:call in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:62
#12 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php:962
#11 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#10 call_user_func_array in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
#9 Illuminate\Routing\Route:run in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1028
#8 Illuminate\Routing\Router:dispatchToRoute in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php:996
#7 Illuminate\Routing\Router:dispatch in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:776
#6 Illuminate\Foundation\Application:dispatch in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:746
#5 Illuminate\Foundation\Application:handle in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/html/learninglocker/subdomains/live/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/html/learninglocker/subdomains/live/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:642
#0 Illuminate\Foundation\Application:run in /var/www/html/learninglocker/subdomains/live/public/index.php:49

**Comment by ryansmith94** [comment] 2015-12-10 14:23
Duplicate of #760.

**Closed by ryansmith94** 2015-12-10 14:23 UTC
