### ISSUE TITLE
Articulate storyline 2 and Grassbalde reporting issue

### ISSUE THREAD

**Issue by yashbantm** [LearningLocker/learninglocker#878] opened 2016-10-27 07:47 UTC
Hi all,

I have developed an emodule using Articulate Story line 2 and published it for LRS report(Grassblade LRS) but its showing "Configuration data is missing or incorrect. Please try again." error.

Please help me, please find my published URL below

http://mednl.com/tincantest/c1/story.html?endpoint=http://eptral.com/grassblade-lrs/xAPI/&auth=MTQtNDVlNjYwNmU2YjkwYjc2OmEyYmZkNTJhYWNmN2UwNjdhYTk3YTdkZjc=&actor={"mbox":"mailto:ex@mple.co.uk", "name":"Example User"}&activity_id=5pmXx3XAGvX_course_id&registration=2981c910-6445-11e4-9803-0800200c9a66

**Comment by ht2** [comment] 2016-10-27 07:53
Sorry, can I clarify what this has to do with Learning Locker?

**Comment by ht2** [comment] 2016-10-27 08:54
Duplicate of #879

**Closed by ht2** 2016-10-27 08:54 UTC

**Comment by yashbantm** [comment] 2016-10-27 08:55
Hi can i use learning locker for the above problem to i mean does learning locker could help us to published our articulate based emodules and send the report to LL LRS?

**Comment by yashbantm** [comment] 2016-10-27 15:38
Hi,

 

We are planning to shift our LMS to LRS for that we need to convert and republished all our articulate storyline 2 based modules 


into LRS. We just need your help to understand how could your LRS support us and we do this please reply.

 

 

Thanks & Regards

Yash.

**Comment by hallshouse** [comment] 2016-10-27 16:01
@yashbantm 
I have dozens of clients using LearningLocker with Storyline courses.
Here is what you need to know:
1. Learning Locker is a data receiver, storage and reporting facility for data created from Storyline.
2. LearningLocker (like GrassBlade) has no facility to upload storyline published ZIP files.
3. You need to have another software product to upload you Storyline ZIP files and to also create properly formatted information that lets you send data to LearningLocker (just like with Grassblade).


To understand a full picture of how to get Storyline to publish to ANY LRS, go to the E-Learning Heros website or search the internet.

If you are using WordPress as you LMS platform, get my free TIN-CAN Manager plugin from http://learning-templates.com
If my free plugin is to complicated for you, get my paid version "TIN-CAN Manager Basic" so you can just click a button and all the technical stuff will be gone for you.

To help you become more informed about the whole process and requirements to run xAPI content for ANY LRS:
Step 1: Watch the YouTube video I sent you earlier to learn how to publish a storyline project for xAPI.
Step 2: Read this Articulate article: https://community.articulate.com/discussions/articulate-storyline/capture-tin-can-api-statements-generated-by-storyline

Once you have done the previous and you still have informed questions, come back here and ask an informed question.
