### ISSUE TITLE
Export doesn't work for some LRS?

### ISSUE THREAD

**Issue by mcarropellicer** [LearningLocker/learninglocker#805] opened 2016-04-13 08:21 UTC
I have installed Learning Locker and it's working fine with some LMS sources.

I found one annoying thing, the export option works for some of the LRS but doesn't work for a particular one, where can i get more info about the problem? I see no errors at the log.

Thanks for any help

**Comment by ryansmith94** [comment] 2016-04-13 08:26
Hi @mcarropellicer, thanks for reporting this issue. Can you please answer the following questions:

1. How many statements are in the LRS that doesn't work?
2. How many statements are in the LRS that does work?
3. What filters are you using in your export?
4. What do you mean by "doesn't work"?

**Comment by mcarropellicer** [comment] 2016-04-13 08:30
I don't want to call it "issue" as some LRS works perfectly!

About your questions:

1. Statements 350
2. Statements 447
3 and 4. The button export does nothing if i click it!

Thanks for the quick response, it's not urgent, just weird.

**Comment by ryansmith94** [comment] 2016-04-13 08:38
Ok my reason for the two questions, is that I thought perhaps the download was just taking a long time to start (although it shouldn't).

Can you please open the developer console in your browser and go to the network tab (if you don't know how to do this, tell me which browser you have, then I can provide you with instructions). When you export, a new entry (for the request to the LRS) should appear in the network tab. Can you tell me if this happens?

You're very welcome, ok, it certainly is weird.

**Comment by mcarropellicer** [comment] 2016-04-13 09:21
I'm using Chrome, I noticed that appears a JS error, here is the screenshot:

http://imgur.com/k6S3X8z

The error does not appear in the other LRSs.

Thanks again

**Comment by ryansmith94** [comment] 2016-04-13 10:00
Hmmm what version of LL are you using?

**Comment by mcarropellicer** [comment] 2016-04-13 10:04
Latest, 1.12.1

**Comment by ryansmith94** [comment] 2016-04-13 10:09
Ok.

@andrewhickey @ht2 not really sure how it's possible for the id to not exist since I assume it'd have to know the id to fetch. Can someone look into this at some point?

**Comment by ht2** [comment] 2016-04-13 10:24
@mcarropellicer Can I check, do you have an existing report that you are trying to export when it fails?

**Comment by ht2** [comment] 2016-04-13 10:29
Also can I clarify: 
`The button export does nothing if i click it!`

Which button are you referring to? There is the download button within an Export? In which case, is it failing on JSON, CSV or both?

**Comment by mcarropellicer** [comment] 2016-04-13 10:33
Sorry, i need to explain it better:

It's the button "+ Add export", i'm unable to create the export for that particular LRS, the others works fine!

More info, the first image shows the problem, the second shows the normal behaviour:

http://imgur.com/a/iNRSd

I really appreciate your help

**Comment by ht2** [comment] 2016-04-13 10:38
Gotcha!! I think this is actually "kind of" expected behavior.... you can't create an export in an LRS that has no reports to export! If you look in the Reports page I'd bet good money that there are no reports in the LRS where it fails and there are reports in the LRS where it doesn't. 

The handling of the error isn't great and there should probably be some alert on that page if no reports exist but its actually preventing you doing something that wouldn't work anyway.

**Comment by mcarropellicer** [comment] 2016-04-13 10:38
Ok, i think i discovered the problem.

To create an export, you need to create a report first, so no problem at all.

Maybe will be good if appears a warn or something that indicates you need to create a report.

Thanks!

**Comment by mcarropellicer** [comment] 2016-04-13 10:39
We got it at the same time haha, sorry for disturbing you, was obvious!

PS: IMO Showing a warn message will be good in terms of usability.

**Comment by ht2** [comment] 2016-04-13 10:43
No problem, I've created a separate issue and I'll close this one out

**Closed by ht2** 2016-04-13 10:43 UTC
Labels: priority:low, status:confirmed, type:bug
